/** Explicit, bounded GPU editing queries. No CPU tessellation or transform evaluation. */
import { split64 } from '../model/index.js';
export const EDIT_BINDINGS={clearSelection:[0,4,5],markSelection:[0,4,5],snapEntity:[0,1,2,3],bakeExplode:[0,1,2],snapCandidates:[0,1,2,3,6,7],reduceSnap:[0,3]};
function queued(e,fn){const next=e.queryTail.catch(()=>{}).then(fn);e.queryTail=next;return next;}
function epoch(e){return [e.sceneEpoch,e.camera.x,e.camera.y,e.camera.zoom,e.camera.angle||0].join('/');}
function uniform(e,label){return e.buffer(label,64,GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST);}
export function normalizeRanges(ranges,max){if(!Array.isArray(ranges)||ranges.length>4096)throw new RangeError('At most 4,096 source selections per command.');const sorted=ranges.map(r=>({first:Number(r.first),count:Number(r.count)})).sort((a,b)=>a.first-b.first),out=[];for(const r of sorted){if(!Number.isSafeInteger(r.first)||!Number.isSafeInteger(r.count)||r.first<1||r.count<0||r.first+r.count-1>max)throw new RangeError('Invalid entity selection interval.');if(!r.count)continue;const prev=out.at(-1);if(prev&&r.first<=prev.first+prev.count)prev.count=Math.max(prev.first+prev.count,r.first+r.count)-prev.first;else out.push({...r});}return out;}
export function selectRanges(e,ranges=[]){const next=normalizeRanges(ranges,e.model?.count||0),previous=e.selectionRanges||[];if(JSON.stringify(next)===JSON.stringify(previous))return;const entries=[...previous,...next],data=new Uint32Array(Math.max(4,entries.length*4));let totalOld=0,totalNew=0;entries.forEach((r,i)=>{const before=i<previous.length?totalOld:totalNew;data.set([r.first,r.count,before,0],i*4);if(i<previous.length)totalOld+=r.count;else totalNew+=r.count;});const bytes=data.byteLength+64;if(e.allocatedBytes()+bytes>e.options.memoryBudget)throw new Error('Selection command exceeds the GPU budget.');let params,buffer;try{params=uniform(e,'Selection range counts');buffer=e.buffer('Selected source intervals',data.byteLength,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST,data);const u=new Uint32Array(16);u.set([previous.length,next.length,totalOld,totalNew],8);e.device.queue.writeBuffer(params,0,u);const encoder=e.device.createCommandEncoder({label:'GPU source-selection mask'}),pass=encoder.beginComputePass();for(const [entry,n] of [['clearSelection',totalOld],['markSelection',totalNew]]){if(!n)continue;pass.setPipeline(e.pipelines[entry]);pass.setBindGroup(0,e.group(entry,{0:params,4:buffer,5:e.styleBuffer},EDIT_BINDINGS[entry]));const count=Math.ceil(n/256);pass.dispatchWorkgroups(Math.min(65535,count),Math.ceil(count/65535));}pass.end();e.device.queue.submit([encoder.finish()]);e.selectionRanges=next;e.metrics.bytesUploaded+=bytes;e.metrics.blockSelectionUploadBytes=bytes;e.requestFrame();}finally{params?.destroy();buffer?.destroy();}}
export async function snapPoint(e,x,y,{radius=12,modes=15}={}){
 if(!Number.isFinite(x)||!Number.isFinite(y)||!Number.isFinite(radius)||radius<=0||radius>24||!Number.isInteger(modes)||modes<0||modes>15)throw new RangeError('Invalid snap query.');if(!e.model||e.preparing||e.disposed)return null;const stamp=epoch(e);
 return queued(e,async()=>{if(stamp!==epoch(e)||e.preparing||e.disposed)return null;const pages=e.viewPages||e.pages,total=pages.reduce((n,p)=>n+p.leaves,0);if(!total)return null;let result,lease;const params=[];e.queryBusy=true;
  try{const bytes=(total+1)*32+(pages.length+1)*64+32;e.trimPaperCaches(bytes);if(e.allocatedBytes()+bytes>e.options.memoryBudget)throw new Error('Snap scratch exceeds the GPU budget.');result=e.buffer('GPU spatial snap candidates',(total+1)*32,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_SRC);lease=e.readbacks.acquire(32);const encoder=e.device.createCommandEncoder({label:'GPU-only object snap, bounded winning-point readback'}),pass=encoder.beginComputePass(),[wx,wy]=e.worldAt(x,y);let offset=1;
   for(const page of pages){const origin=page.source.origin||e.model.origin,[xh,xl]=split64(wx-origin[0]),[yh,yl]=split64(wy-origin[1]),[oxh,oxl]=split64(origin[0]),[oyh,oyl]=split64(origin[1]),data=new ArrayBuffer(64),f=new Float32Array(data),u=new Uint32Array(data);f.set([oxh,oyh,oxl,oyl]);f.set([xh,yh,xl,yl],4);u.set([page.count,modes,offset,page.leaves],8);f[12]=radius/e.camera.zoom;offset+=page.leaves;const buffer=uniform(e,'Snap page parameters');params.push(buffer);e.device.queue.writeBuffer(buffer,0,data);pass.setPipeline(e.pipelines.snapCandidates);pass.setBindGroup(0,e.group('snapCandidates',{0:buffer,1:page.entities,2:page.aux,3:result,6:page.bounds,7:e.layerBuffer},EDIT_BINDINGS.snapCandidates));pass.dispatchWorkgroups(page.leaves);}
   const last=uniform(e,'Snap global reduction count');params.push(last);const data=new Uint32Array(16);data[8]=total;e.device.queue.writeBuffer(last,0,data);pass.setPipeline(e.pipelines.reduceSnap);pass.setBindGroup(0,e.group('reduceSnap',{0:last,3:result},EDIT_BINDINGS.reduceSnap));pass.dispatchWorkgroups(1);pass.end();encoder.copyBufferToBuffer(result,0,lease.buffer,0,32);e.device.queue.submit([encoder.finish()]);await lease.buffer.mapAsync(GPUMapMode.READ);const copy=lease.buffer.getMappedRange(0,32).slice(0),rf=new Float32Array(copy),ru=new Uint32Array(copy);e.metrics.bytesUploaded+=params.length*64;e.metrics.bytesReadback+=32;e.metrics.blockSnapReadbackBytes=32;if(stamp!==epoch(e)||!ru[7])return null;return {point:[rf[0]+rf[2],rf[1]+rf[3]],kind:['','Endpoint','Midpoint','Center','Quadrant','Insertion'][ru[4]],id:ru[5],distance:Math.sqrt(rf[6])};
  }finally{lease?.release();for(const p of params)p.destroy();result?.destroy();e.queryBusy=false;}});
}
/** Explicit export/edit boundary: bounded readback only on the user's explode command. */
export function explodeGeometry(e,ranges,{maxEntities=100000,maxBytes=128*1024*1024}={}){const selected=normalizeRanges(ranges,e.model?.count||0),stamp=e.sceneEpoch;return queued(e,async()=>{
 if(e.disposed||e.preparing||stamp!==e.sceneEpoch)throw new Error('The drawing changed before GPU explode.');const slices=[];for(const range of selected)for(const page of e.pages){const start=Math.max(range.first,page.idBase+1),end=Math.min(range.first+range.count,page.idBase+page.count+1);if(end>start)slices.push({page,start:start-page.idBase-1,count:end-start});}
 const total=slices.reduce((n,s)=>n+s.count,0),bytes=slices.reduce((n,s)=>n+s.count*128+s.page.aux.size,0);if(total>maxEntities||bytes>maxBytes)throw new RangeError('GPU explode exceeds the explicit 100,000-entity / 128 MiB command budget.');const output=[];e.queryBusy=true;
 try{for(const slice of slices){if(stamp!==e.sceneEpoch)throw new Error('The drawing changed during GPU explode.');const {page,start,count}=slice,entityBytes=count*128,auxBytes=page.aux.size,readBytes=entityBytes+auxBytes;let params,entities,aux,readback;try{
  const peak=64+2*readBytes;e.trimPaperCaches(peak);if(e.allocatedBytes()+peak>e.options.memoryBudget)throw new Error('GPU explode scratch and explicit readback exceed the GPU budget.');
  params=uniform(e,'Explode world origin');entities=e.buffer('Transactional explode entities',entityBytes,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC);aux=e.buffer('Transactional explode auxiliary',auxBytes,GPUBufferUsage.STORAGE|GPUBufferUsage.COPY_DST|GPUBufferUsage.COPY_SRC);readback=e.buffer('Explicit exploded DXF geometry',readBytes,GPUBufferUsage.MAP_READ|GPUBufferUsage.COPY_DST);
  const data=new ArrayBuffer(64),f=new Float32Array(data),u=new Uint32Array(data),origin=page.source.origin||e.model.origin,[xh,xl]=split64(origin[0]),[yh,yl]=split64(origin[1]);f.set([xh,yh,xl,yl]);u[8]=count;e.device.queue.writeBuffer(params,0,data);
  const encoder=e.device.createCommandEncoder({label:'GPU affine explode; original scene is never modified'});encoder.copyBufferToBuffer(page.entities,start*128,entities,0,entityBytes);encoder.copyBufferToBuffer(page.aux,0,aux,0,auxBytes);const pass=encoder.beginComputePass();pass.setPipeline(e.pipelines.bakeExplode);pass.setBindGroup(0,e.group('bakeExplode',{0:params,1:entities,2:aux},EDIT_BINDINGS.bakeExplode));pass.dispatchWorkgroups(Math.ceil(count/64));pass.end();encoder.copyBufferToBuffer(entities,0,readback,0,entityBytes);encoder.copyBufferToBuffer(aux,0,readback,entityBytes,auxBytes);e.device.queue.submit([encoder.finish()]);await readback.mapAsync(GPUMapMode.READ);const copy=readback.getMappedRange().slice(0),check=new Uint32Array(copy,0,count*32);for(let i=0;i<count;i++)if(!check[i*32+16])throw new Error('Explode rejected an unsupported affine primitive, wrapped text, or nonuniform bulged polyline. No source objects were changed.');output.push({entities:copy.slice(0,entityBytes),aux:copy.slice(entityBytes),count,handles:page.source.handles?.slice(start,start+count)||[]});e.metrics.bytesUploaded+=64;e.metrics.bytesReadback+=readBytes;
 }finally{readback?.destroy();params?.destroy();entities?.destroy();aux?.destroy();}}if(stamp!==e.sceneEpoch)throw new Error('The drawing changed during GPU explode.');e.metrics.blockExplodeReadbackBytes=bytes;return output;}finally{e.queryBusy=false;}});}
