import { EMPTY_DXF } from './template.js';
import { serializedRecord } from './serialize.js';
/** Editable DXF block graph. No entity tessellation or rasterization occurs here.
 * Raw records remain immutable between transactions; history shares unchanged records.
 * Attributes are normalized to standard DXF WCS text parameters at the file boundary.
 */
import { asciiGroups, binaryGroups, records } from '../dxf/index.js';
export const BLOCK_SCHEMA = 'aperture.block-library/1';
export const UNIT_NAMES = ['Unitless','Inches','Feet','Miles','Millimeters','Centimeters','Meters','Kilometers','Microinches','Mils','Yards','Angstroms','Nanometers','Microns','Decimeters','Decameters','Hectometers','Gigameters','Astronomical units','Light years','Parsecs','US survey feet','US survey inches','US survey yards','US survey miles'];
const METERS=[1,.0254,.3048,1609.344,.001,.01,1,1000,2.54e-8,2.54e-5,.9144,1e-10,1e-9,1e-6,.1,10,100,1e9,149597870700,9.4607304725808e15,3.085677581491367e16,1200/3937,100/3937,3600/3937,6336000/3937];
export const group=(r,c,d=0)=>r?.groups?.find(g=>g.code===c)?.value??d;
export const canonical=n=>String(n).toLocaleUpperCase('en-US');
export function setGroup(r,c,value){const groups=r.groups.map(g=>({...g})),i=groups.findIndex(g=>g.code===c);if(i<0)groups.push({code:c,value});else groups[i]={code:c,value};return {...r,groups};}
export function record(type,values=[]){return {type,groups:values.map(([code,value])=>({code,value}))};}
const clone=globalThis.structuredClone;
const DEG=Math.PI/180;
const finite=(n,name)=>{n=Number(n);if(!Number.isFinite(n)||!Number.isFinite(Math.fround(n)))throw new RangeError(name+' must be finite.');return n;};
export function validateName(name,{anonymous=false}={}){name=String(name).trim();if(!name||name.length>255||/[\x00-\x1f<>/\\":;?\|=]/.test(name)||(!anonymous&&name.includes('*')))throw new RangeError('Use a block name of 1–255 characters without DXF-reserved punctuation.');return name;}
export function unitFactor(from,to){if(!Number.isInteger(from)||!Number.isInteger(to)||!METERS[from]||!METERS[to])throw new RangeError('Unknown insertion units.');return !from||!to?1:METERS[from]/METERS[to];}
function decode(input){if(typeof input==='string')return input;if(!(input instanceof ArrayBuffer))throw new TypeError('DXF input must be text or an ArrayBuffer.');const head=new TextDecoder().decode(new Uint8Array(input,0,Math.min(65536,input.byteLength)));if(head.startsWith('AutoCAD Binary DXF'))return null;const ver=/\$ACADVER\s*\r?\n\s*1\s*\r?\n\s*AC(\d+)/.exec(head),cp=/\$DWGCODEPAGE\s*\r?\n\s*3\s*\r?\n\s*ANSI_(\d+)/.exec(head);let encoding=ver&&Number(ver[1])>=1021?'utf-8':cp?'windows-'+cp[1]:'windows-1252';try{return new TextDecoder(encoding).decode(input);}catch{return new TextDecoder('windows-1252').decode(input);}}
function fold(items){const out=[];for(let i=0;i<items.length;i++){let r=items[i];if(r.type==='INSERT'&&group(r,66,0)===1){const attributes=[];while(items[i+1]?.type==='ATTRIB')attributes.push(items[++i]);const seqend=items[i+1]?.type==='SEQEND'?items[++i]:record('SEQEND');r={...r,attributes,seqend};}else if(r.type==='POLYLINE'){const vertices=[];while(items[i+1]?.type==='VERTEX')vertices.push(items[++i]);const seqend=items[i+1]?.type==='SEQEND'?items[++i]:record('SEQEND');r={...r,vertices,seqend};}out.push(r);}return out;}
function flatten(items){const out=[];for(const r of items){out.push(r);if(r.vertices){out.push(...r.vertices,r.seqend||record('SEQEND'));}if(r.attributes?.length||group(r,66,0)===1){out.push(...(r.attributes||[]),r.seqend||record('SEQEND'));}}return out;}
function cleanRecord(r){const copy=clone(r);copy.groups=copy.groups.filter(g=>![5,105,330,360,67,410].includes(g.code)&&g.code!==102);delete copy.seqend;for(const key of ['attributes','vertices'])if(copy[key])copy[key]=copy[key].map(cleanRecord);return copy;}
function bytesOf(state){return new TextEncoder().encode(JSON.stringify(state)).length;}
export function insertOptions(values={}){
 const position=(values.position||[0,0,0]).map((v,i)=>finite(v,'Position '+i));while(position.length<3)position.push(0);if(position.length!==3)throw new RangeError('Position requires two or three coordinates.');
 const scale=(values.scale||[1,1,1]).map((v,i)=>{v=finite(v,'Scale '+i);if(Math.abs(v)<1e-12)throw new RangeError('An INSERT scale cannot be zero.');return v;});while(scale.length<3)scale.push(1);if(scale.length!==3)throw new RangeError('Scale requires two or three coordinates.');
 const count=(v,label)=>{v=Number(v??1);if(!Number.isSafeInteger(v)||v<1||v>32767)throw new RangeError(label+' must be an integer from 1 to 32,767.');return v;};
 const rows=count(values.rows,'Rows'),columns=count(values.columns,'Columns');if(rows*columns>1000000)throw new RangeError('Array exceeds one million placements.');
 return {position,scale,rotation:finite(values.rotation??0,'Rotation'),rows,columns,rowSpacing:finite(values.rowSpacing??0,'Row spacing'),columnSpacing:finite(values.columnSpacing??0,'Column spacing'),layer:String(values.layer||'0'),color:Number(values.color??256),attributes:{...(values.attributes||{})},space:String(values.space||'model')};
}
export function recordSpace(r){const name=String(group(r,410,''));return name?(canonical(name)==='MODEL'?'model':'layout:'+name):group(r,67)?'layout:Layout1':'model';}
export function readInsert(r){return insertOptions({position:[group(r,10),group(r,20),group(r,30)],scale:[group(r,41,1),group(r,42,1),group(r,43,1)],rotation:group(r,50),columns:group(r,70,1),rows:group(r,71,1),columnSpacing:group(r,44),rowSpacing:group(r,45),layer:group(r,8,'0'),color:group(r,62,256),space:recordSpace(r),attributes:Object.fromEntries((r.attributes||[]).map(a=>[String(group(a,2,'')),String(group(a,1,''))]))});}
/** Standard ATTRIB text parameters. Only serialization math; rendering still evaluates nodes on GPU. */
export function attributeFor(def,block,options,handle){
 const o=insertOptions(options),a=o.rotation*DEG,c=Math.cos(a),s=Math.sin(a),sx=o.scale[0],sy=o.scale[1],base=block.base;
 const transform=(x,y)=>[o.position[0]+c*sx*(x-base[0])-s*sy*(y-base[1]),o.position[1]+s*sx*(x-base[0])+c*sy*(y-base[1])];
 const angle=group(def,50)*DEG,h=group(def,40,1),w=group(def,41,1),ob=group(def,51)*DEG,ca=Math.cos(angle),sa=Math.sin(angle),map=(x,y)=>[c*sx*x-s*sy*y,s*sx*x+c*sy*y];
 const x=map(ca*h*w,sa*h*w),y=map((ca*Math.tan(ob)-sa)*h*((group(def,71,0)&4)?-1:1),(sa*Math.tan(ob)+ca)*h*((group(def,71,0)&4)?-1:1)),length=Math.hypot(...x);if(length<1e-15)throw new RangeError('Degenerate attribute text basis.');
 const ux=x[0]/length,uy=x[1]/length,vertical=ux*y[1]-uy*y[0],height=Math.abs(vertical);if(height<1e-15)throw new RangeError('Degenerate attribute height.');
 let r=cleanRecord(def);r.type='ATTRIB';r.groups=r.groups.filter(g=>g.code!==3&&g.code!==100);r=setGroup(r,5,handle);r=setGroup(r,100,'AcDbEntity');
 const tag=String(group(def,2,'')),flags=group(def,70,0),value=(flags&2)?String(group(def,1,'')):String(o.attributes[tag]??group(def,1,''));
 const p=transform(group(def,10),group(def,20));for(const [code,field] of [[1,value],[10,p[0]],[20,p[1]],[30,o.position[2]+(group(def,30)-base[2])*o.scale[2]],[40,height],[41,length/height],[50,Math.atan2(uy,ux)/DEG],[51,Math.atan2((ux*y[0]+uy*y[1])*Math.sign(vertical),height)/DEG],[71,(group(def,71,0)&2)|(vertical<0?4:0)],[74,group(def,74,group(def,73,0))],[8,group(def,8,'0')==='0'?o.layer:group(def,8)]])r=setGroup(r,code,field);
 if(def.groups.some(g=>g.code===11)){const p=transform(group(def,11),group(def,21));r=setGroup(setGroup(r,11,p[0]),21,p[1]);}
 r.groups=r.groups.filter(g=>g.code!==73);return r;
}
export class BlockDrawing {
 constructor(input=null,{name='Drawing.dxf',maxBytes=256*1024*1024,maxRecords=2000000}={}){
  this.name=name;this.sections=[];this.blocks=[];this.entities=[];this.tables=[];this.undoStack=[];this.redoStack=[];this.revision=0;this.maxHistory=64;this.serial=0x100000n;this.warnings=[];
  if(input===null)input=EMPTY_DXF;
  if(input!==null){const size=typeof input==='string'?input.length*2:input.byteLength;if(size>maxBytes)throw new RangeError('Editable DXF source exceeds the 256 MiB safety budget.');const text=decode(input);let sec=null,n=0;for(const r of records(text===null?binaryGroups(input):asciiGroups(text))){if(++n>maxRecords)throw new RangeError('Editable DXF record limit exceeded.');if(r.type==='SECTION'){sec={name:String(group(r,2,'')),header:r,records:[]};this.sections.push(sec);}else if(r.type==='ENDSEC'){sec=null;}else if(r.type==='EOF')break;else if(sec)sec.records.push(r);}}
  if(!this.sections.length)this.sections=[{name:'HEADER',header:record('SECTION',[[2,'HEADER'],[9,'$ACADVER'],[1,'AC1021'],[9,'$INSUNITS'],[70,0]]),records:[]},{name:'TABLES',header:record('SECTION',[[2,'TABLES']]),records:[]},{name:'BLOCKS',header:record('SECTION',[[2,'BLOCKS']]),records:[]},{name:'ENTITIES',header:record('SECTION',[[2,'ENTITIES']]),records:[]}];
  this.tables=this.sections.find(s=>s.name==='TABLES')?.records||[];
  const flat=this.sections.find(s=>s.name==='BLOCKS')?.records||[];let b=null;for(const r of flat){if(r.type==='BLOCK'){if(b)throw new Error('Unterminated BLOCK definition.');b={header:r,records:[],end:record('ENDBLK')};}else if(r.type==='ENDBLK'){if(b){b.end=r;b.records=fold(b.records);this.blocks.push(b);b=null;}}else if(b)b.records.push(r);}if(b)throw new Error('Unterminated BLOCK definition.');
  this.entities=fold(this.sections.find(s=>s.name==='ENTITIES')?.records||[]);this.normalizeSpaces();this.scanHandles();this.ensureHandles();this.refresh();
 }
 layoutBindings(){const result=new Map();for(const section of this.sections)for(const r of section.records)if(r.type==='LAYOUT'){const at=r.groups.findIndex(g=>g.code===100&&g.value==='AcDbLayout'),values=at>=0?r.groups.slice(at+1):r.groups,name=String(values.find(g=>g.code===1)?.value||''),owner=values.filter(g=>g.code===330).at(-1)?.value;if(name&&owner)result.set(canonical(name),{name,owner:String(owner)});}return result;}
 normalizeSpaces(){const layouts=this.layoutBindings(),byOwner=new Map([...layouts.values()].map(x=>[canonical(x.owner),x.name])),tableName=new Map(this.tables.filter(r=>r.type==='BLOCK_RECORD').map(r=>[canonical(group(r,2)),String(group(r,5))])),seen=new Set(this.entities.map(r=>String(group(r,5,''))).filter(Boolean));const normalize=(r,name,owner)=>{const explicit=String(group(r,410,'')),resolved=explicit||name||byOwner.get(canonical(group(r,330,'')))||(group(r,67)?'Layout1':'Model');r=setGroup(r,410,resolved);r=setGroup(r,67,canonical(resolved)==='MODEL'?0:1);const binding=layouts.get(canonical(resolved));if(binding||owner)r=setGroup(r,330,binding?.owner||owner);return r;};this.entities=this.entities.map(r=>normalize(r));this.blocks=this.blocks.map(b=>{const name=String(group(b.header,2,''));if(!/^[*$](?:model_space|paper_space)/i.test(name))return b;const owner=tableName.get(canonical(name))||String(group(b.header,330,'')),layout=byOwner.get(canonical(owner))||(/model_space/i.test(name)?'Model':'Layout1');for(const r of b.records){const h=String(group(r,5,''));if(!h||!seen.has(h)){this.entities.push(normalize(r,layout,owner));if(h)seen.add(h);}}return {...b,records:[]};});}
 scanHandles(){for(const sec of this.sections)for(const r of [sec.header,...sec.records]){const h=String(group(r,5,group(r,105,'')));if(/^[0-9a-f]+$/i.test(h)){const x=BigInt('0x'+h);if(x>=this.serial)this.serial=x+1n;}}}
 nextHandle(){return (this.serial++).toString(16).toUpperCase();}
 reserveHandles(items){const visit=r=>{const h=String(group(r,5,group(r,105,'')));if(/^[0-9a-f]{1,64}$/i.test(h)){const n=BigInt('0x'+h);if(n>=this.serial)this.serial=n+1n;}for(const key of ['attributes','vertices'])r[key]?.forEach(visit);if(r.seqend)visit(r.seqend);};items.forEach(visit);}
 ensureHandles(){const stamp=r=>{let n=r;if(!group(n,5,''))n=setGroup(n,5,this.nextHandle());if(n.attributes)n={...n,attributes:n.attributes.map(stamp)};if(n.vertices)n={...n,vertices:n.vertices.map(stamp)};if(n.attributes?.length||n.vertices||group(n,66,0)===1)n={...n,seqend:stamp(n.seqend||record('SEQEND'))};return n;};this.entities=this.entities.map(stamp);this.blocks=this.blocks.map(b=>({...b,header:stamp(b.header),end:stamp(b.end),records:b.records.map(stamp)}));}
 refresh(){this.blockMap=new Map();for(const b of this.blocks){const name=String(group(b.header,2,'')),k=canonical(name);if(this.blockMap.has(k))throw new Error('Duplicate case-insensitive block definition: '+name);this.blockMap.set(k,b);}this.entityMap=new Map(this.entities.map(r=>[String(group(r,5)),r]));}
 get units(){const s=this.sections.find(s=>s.name==='HEADER');const g=[...(s?.header.groups||[]),...(s?.records.flatMap(r=>r.groups)||[])];const i=g.findIndex(v=>v.code===9&&v.value==='$INSUNITS');return i>=0?Number(g[i+1]?.value||0):0;}
 get layers(){const items=this.tables.filter(r=>r.type==='LAYER').map(r=>({name:String(group(r,2)),locked:!!(group(r,70)&4),color:group(r,62,7)}));if(!items.some(l=>l.name==='0'))items.unshift({name:'0',locked:false,color:7});return items;}
 metadata(b){if(typeof b==='string')b=this.definition(b);const name=String(group(b.header,2)),table=this.tables.find(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2,''))===canonical(name));return {name,base:[group(b.header,10),group(b.header,20),group(b.header,30)],description:String(group(b.header,4,'')),flags:group(b.header,70),units:group(table,70,this.units),allowExplode:group(table,280,1)!==0,uniform:group(table,281,0)!==0,external:!!(group(b.header,70)&12),dynamic:/^\*U/i.test(name)||[b.header,table].some(r=>r?.groups.some(g=>String(g.value)==='ACAD_ENHANCEDBLOCK')),anonymous:name.startsWith('*'),system:/^[*$](?:model_space|paper_space)/i.test(name),path:String(group(b.header,1,'')),count:b.records.length,attributes:b.records.filter(r=>r.type==='ATTDEF').map(r=>({tag:String(group(r,2)),prompt:String(group(r,3,group(r,2))),value:String(group(r,1,'')),constant:!!(group(r,70)&2),invisible:!!(group(r,70)&1),preset:!!(group(r,70)&8),verify:!!(group(r,70)&4),locked:!!group(r,280,0)})),dependencies:[...new Set(b.records.filter(r=>r.type==='INSERT').map(r=>String(group(r,2))))]};}
 definition(name){const b=this.blockMap.get(canonical(name));if(!b)throw new Error('Block definition not found: '+name);return b;}
 list({includeSystem=false}={}){return this.blocks.map(b=>this.metadata(b)).filter(b=>includeSystem||!b.system);}
 snapshot(){return {blocks:this.blocks,entities:this.entities,tables:this.tables,sections:this.sections};}
 restore(s){Object.assign(this,s);this.refresh();}
 transaction(label,fn){if(this.transactionDepth){const result=fn();this.ensureHandles();this.refresh();return result;}const before=this.snapshot();this.transactionDepth=1;try{const result=fn();this.ensureHandles();this.refresh();this.validateGraph();this.undoStack.push({label,before,after:this.snapshot()});if(this.undoStack.length>this.maxHistory)this.undoStack.shift();this.redoStack=[];this.revision++;return result;}catch(error){this.restore(before);throw error;}finally{this.transactionDepth=0;}}
 undo(){const c=this.undoStack.pop();if(!c)return false;this.restore(c.before);this.redoStack.push(c);this.revision++;return c.label;}
 redo(){const c=this.redoStack.pop();if(!c)return false;this.restore(c.after);this.undoStack.push(c);this.revision++;return c.label;}
 validateGraph(){for(const b of this.blocks){const tags=new Set();for(const r of b.records)if(r.type==='ATTDEF'){const tag=canonical(group(r,2,''));if(!tag||tags.has(tag))throw new Error('Duplicate or empty attribute tag in '+group(b.header,2)+': '+tag);tags.add(tag);}const stack=[{name:String(group(b.header,2)),path:[]}];let visited=0;while(stack.length){const f=stack.pop(),key=canonical(f.name);if(f.path.includes(key))throw new Error('Cyclic block reference: '+[...f.path,key].join(' → '));if(f.path.length>=48)throw new RangeError('Nested blocks exceed the safe depth of 48.');if(++visited>100000)throw new RangeError('Block dependency expansion exceeds the safety budget.');const d=this.blockMap.get(key);if(!d)continue;for(const r of d.records)if(r.type==='INSERT')stack.push({name:String(group(r,2)),path:[...f.path,key]});}}}
 dependencyNames(name){const out=[],seen=new Set(),stack=[name];while(stack.length){const n=stack.pop(),k=canonical(n);if(seen.has(k))continue;seen.add(k);const b=this.definition(n);out.push(String(group(b.header,2)));for(const r of b.records)if(r.type==='INSERT')stack.push(String(group(r,2)));}return out;}
 references(name=null){const rows=[];const visit=(items,parent=null,path=[])=>{for(const r of items){if(r.type!=='INSERT')continue;const n=String(group(r,2)),id=String(group(r,5));if(name===null||canonical(name)===canonical(n))rows.push({id,name:n,parent,path:[...path,id],layer:String(group(r,8,'0')),options:readInsert(r)});}};visit(this.entities);for(const b of this.blocks)visit(b.records,String(group(b.header,2)));return rows;}
 tree(name,path=[],budget={left:10000}){if(--budget.left<0)return {name,truncated:true,children:[]};const key=canonical(name);if(path.includes(key))return {name,cycle:true,children:[]};if(path.length>=48)return {name,truncated:true,children:[]};const b=this.blockMap.get(key);if(!b)return {name,missing:true,children:[]};return {name,entities:b.records.length,children:b.records.filter(r=>r.type==='INSERT').map(r=>({...this.tree(String(group(r,2)),[...path,key],budget),handle:String(group(r,5)),layer:String(group(r,8,'0')),options:readInsert(r)}))};}
 assertEditable(name){const m=this.metadata(name);if(m.system)throw new Error('Model/paper space containers are not user blocks.');if(m.external)throw new Error('External references are listed, but must be bound by the source CAD system before authoring.');if(m.dynamic)throw new Error('Potential dynamic/evaluated block: displayed for inspection, but actions and constraints cannot be edited or regenerated. Export a static block in the originating CAD system first.');return m;}
 ensureLayer(name){name=validateName(name);if(this.layers.some(l=>canonical(l.name)===canonical(name)))return;const r=record('LAYER',[[5,this.nextHandle()],[100,'AcDbSymbolTableRecord'],[100,'AcDbLayerTableRecord'],[2,name],[70,0],[62,7],[6,'CONTINUOUS']]);this.tables=insertTable(this.tables,'LAYER',[r]);}
 blockRecord(name,units=0){if(!Number.isInteger(units)||units<0||units>24)throw new RangeError('Unknown insertion units.');const r=record('BLOCK_RECORD',[[5,this.nextHandle()],[100,'AcDbSymbolTableRecord'],[100,'AcDbBlockTableRecord'],[2,name],[70,units],[280,1],[281,0]]);this.tables=insertTable(this.tables,'BLOCK_RECORD',[r]);return r;}
 makeInsert(name,values={}){const meta=this.assertEditable(name),o=insertOptions(values);if(meta.uniform&&o.scale.some(s=>Math.abs(Math.abs(s)-Math.abs(o.scale[0]))>1e-10))throw new RangeError('This block requires uniform XYZ scale.');const layer=this.layers.find(l=>canonical(l.name)===canonical(o.layer));if(layer?.locked)throw new Error('The insertion layer is locked.');this.ensureLayer(o.layer);let r=record('INSERT',[[5,this.nextHandle()],[100,'AcDbEntity'],[8,o.layer],[62,o.color],[67,o.space==='model'?0:1],[410,o.space==='model'?'Model':o.space.replace(/^layout:/,'')],[100,'AcDbBlockReference'],[2,meta.name],[10,o.position[0]],[20,o.position[1]],[30,o.position[2]],[41,o.scale[0]],[42,o.scale[1]],[43,o.scale[2]],[50,o.rotation],[70,o.columns],[71,o.rows],[44,o.columnSpacing],[45,o.rowSpacing]]);
  const attributes=this.definition(name).records.filter(r=>r.type==='ATTDEF'&&!(group(r,70)&2)).map(a=>attributeFor(a,meta,o,this.nextHandle()));if(attributes.length)r={...setGroup(r,66,1),attributes,seqend:record('SEQEND',[[5,this.nextHandle()],[8,o.layer]])};return r;}
 insert(name,values={}){let id;this.transaction('Insert '+name,()=>{const r=this.makeInsert(name,values);this.entities=[...this.entities,r];id=String(group(r,5));});return id;}
 editInsert(id,patch={}){this.transaction('Edit block reference',()=>{const old=this.entityMap.get(id);if(old?.type!=='INSERT')throw new Error('Select a root INSERT reference.');if(this.layers.find(l=>canonical(l.name)===canonical(group(old,8,'0')))?.locked)throw new Error('The reference layer is locked.');const name=patch.name||String(group(old,2)),values={...readInsert(old),...patch};delete values.name;let r=this.makeInsert(name,values);r=setGroup(r,5,id);this.entities=this.entities.map(e=>e===old?r:e);});}
 deleteEntities(ids){const wanted=new Set(ids);this.transaction('Delete selection',()=>{for(const r of this.entities)if(wanted.has(String(group(r,5)))&&this.layers.find(l=>l.name===group(r,8,'0'))?.locked)throw new Error('Selection contains entities on locked layers.');this.entities=this.entities.filter(r=>!wanted.has(String(group(r,5))));});}
 rename(oldName,newName){newName=validateName(newName);this.transaction('Rename '+oldName,()=>{this.assertEditable(oldName);if(this.blockMap.has(canonical(newName))&&canonical(oldName)!==canonical(newName))throw new Error('A block with that name already exists.');const replace=r=>(r.type==='INSERT'||r.type==='DIMENSION')&&canonical(group(r,2,''))===canonical(oldName)?setGroup(r,2,newName):r;this.entities=this.entities.map(replace);this.blocks=this.blocks.map(b=>({...b,header:canonical(group(b.header,2))===canonical(oldName)?setGroup(setGroup(b.header,2,newName),3,newName):b.header,records:b.records.map(replace)}));this.tables=this.tables.map(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===canonical(oldName)?setGroup(r,2,newName):r);});}
 create(name,ids,base=[0,0,0],{mode='convert',description='',units=this.units}={}){name=validateName(name);let inserted=null;this.transaction('Create '+name,()=>{if(this.blockMap.has(canonical(name)))throw new Error('Block name already exists.');const wanted=new Set(ids),selected=this.entities.filter(r=>wanted.has(String(group(r,5))));if(!selected.length)throw new Error('Select at least one source entity or INSERT.');if(selected.some(r=>r.type==='VIEWPORT'))throw new Error('Paper viewports cannot be block members.');if(new Set(selected.map(r=>recordSpace(r))).size!==1)throw new Error('Create block requires objects from a single model or paper space.');if(selected.some(r=>this.layers.find(l=>canonical(l.name)===canonical(group(r,8,'0')))?.locked))throw new Error('Selection contains entities on locked layers.');if(!['convert','retain','delete'].includes(mode))throw new Error('Unknown block creation mode.');base=[finite(base[0],'Base X'),finite(base[1],'Base Y'),finite(base[2]||0,'Base Z')];const table=this.blockRecord(name,units);const header=record('BLOCK',[[5,this.nextHandle()],[330,group(table,5)],[100,'AcDbEntity'],[8,'0'],[100,'AcDbBlockBegin'],[2,name],[3,name],[70,0],[10,base[0]],[20,base[1]],[30,base[2]],[4,String(description)]]);this.blocks=[...this.blocks,{header,end:record('ENDBLK',[[5,this.nextHandle()],[330,group(table,5)],[100,'AcDbEntity'],[8,'0'],[100,'AcDbBlockEnd']]),records:selected.map(cleanRecord).map(r=>setGroup(r,5,this.nextHandle()))}];this.refresh();if(mode!=='retain')this.entities=this.entities.filter(r=>!wanted.has(String(group(r,5))));if(mode==='convert'){const space=recordSpace(selected[0]),r=this.makeInsert(name,{position:base,space,layer:String(group(selected[0],8,'0'))});this.entities=[...this.entities,r];inserted=String(group(r,5));}});return inserted;}
 setDefinition(name,{base,description,units,records:newRecords,uniform,allowExplode}={}){this.transaction('Edit definition '+name,()=>{const old=this.definition(name);this.assertEditable(name);let header=old.header;if(base){for(let i=0;i<3;i++)header=setGroup(header,10+i*10,finite(base[i]||0,'Base point'));}if(description!==undefined)header=setGroup(header,4,String(description));if(newRecords){validateRecords(newRecords);this.reserveHandles(newRecords);newRecords=clone(newRecords).map(r=>{const handle=group(r,5,'')||this.nextHandle();return setGroup(cleanRecord(r),5,handle);});}this.blocks=this.blocks.map(b=>b===old?{...b,header,records:newRecords||b.records}:b);if(!this.tables.some(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===canonical(name)))this.blockRecord(name,this.units);if(units!==undefined&&(!Number.isInteger(units)||units<0||units>24))throw new RangeError('Unknown insertion units.');this.tables=this.tables.map(r=>{if(r.type!=='BLOCK_RECORD'||canonical(group(r,2))!==canonical(name))return r;for(const [c,v] of [[70,units],[280,allowExplode===undefined?undefined:Number(allowExplode)],[281,uniform===undefined?undefined:Number(uniform)]])if(v!==undefined)r=setGroup(r,c,v);return r;});});}
 addAttribute(name,{tag,prompt='',value='',x=0,y=0,height=2.5,rotation=0,flags=0}={}){tag=validateName(tag).replace(/\s/g,'_').toUpperCase();const b=this.definition(name);if(b.records.some(r=>r.type==='ATTDEF'&&canonical(group(r,2))===canonical(tag)))throw new Error('Attribute tag already exists.');const r=record('ATTDEF',[[5,this.nextHandle()],[8,'0'],[10,finite(x,'X')],[20,finite(y,'Y')],[40,finite(height,'Height')],[50,finite(rotation,'Rotation')],[1,String(value)],[2,tag],[3,String(prompt||tag)],[70,flags|0],[72,0],[74,0]]);if(height<=0)throw new RangeError('Attribute height must be positive.');this.setDefinition(name,{records:[...b.records,r]});}
 setAttribute(name,tag,{tag:newTag,prompt,value,x,y,height,rotation,flags}={}){const b=this.definition(name),old=b.records.find(r=>r.type==='ATTDEF'&&canonical(group(r,2))===canonical(tag));if(!old)throw new Error('Attribute definition not found: '+tag);let next=old;for(const [code,v,label] of [[10,x,'X'],[20,y,'Y'],[40,height,'Height'],[50,rotation,'Rotation']])if(v!==undefined)next=setGroup(next,code,finite(v,label));if(group(next,40,0)<=0)throw new RangeError('Attribute height must be positive.');if(newTag!==undefined)next=setGroup(next,2,validateName(newTag).replace(/\s/g,'_').toUpperCase());if(prompt!==undefined)next=setGroup(next,3,String(prompt));if(value!==undefined)next=setGroup(next,1,String(value));if(flags!==undefined){if(!Number.isInteger(flags)||flags<0||flags>15)throw new RangeError('Attribute flags must be an integer from 0 to 15.');next=setGroup(next,70,flags);}this.setDefinition(name,{records:b.records.map(r=>r===old?next:r)});}
 removeAttribute(name,tag){const b=this.definition(name);this.setDefinition(name,{records:b.records.filter(r=>r.type!=='ATTDEF'||canonical(group(r,2))!==canonical(tag))});}
 moveAttribute(name,tag,delta){if(delta!==1&&delta!==-1)throw new RangeError('Attribute reorder step must be -1 or +1.');const b=this.definition(name),indices=b.records.map((r,i)=>r.type==='ATTDEF'?i:-1).filter(i=>i>=0),index=indices.findIndex(i=>canonical(group(b.records[i],2))===canonical(tag));if(index<0)throw new Error('Attribute definition not found: '+tag);const target=index+delta;if(target<0||target>=indices.length)return false;const records=b.records.slice();[records[indices[index]],records[indices[target]]]=[records[indices[target]],records[indices[index]]];this.setDefinition(name,{records});return true;}
 syncAttributes(name){this.transaction('Synchronize attributes',()=>{this.assertEditable(name);const sync=r=>r.type==='INSERT'&&canonical(group(r,2))===canonical(name)?setGroup(this.makeInsert(name,readInsert(r)),5,String(group(r,5))):r;this.entities=this.entities.map(sync);this.blocks=this.blocks.map(b=>({...b,records:b.records.map(sync)}));});}
 purge(){const used=new Set(),stack=this.entities.filter(r=>['INSERT','DIMENSION'].includes(r.type)).map(r=>String(group(r,2,'')));for(const b of this.blocks)if(this.metadata(b).system)stack.push(String(group(b.header,2)));while(stack.length){const k=canonical(stack.pop());if(used.has(k))continue;used.add(k);for(const r of this.blockMap.get(k)?.records||[])if(['INSERT','DIMENSION'].includes(r.type))stack.push(String(group(r,2,'')));}const removed=this.list().filter(b=>!used.has(canonical(b.name))).map(b=>b.name);this.transaction('Purge unused blocks',()=>{const names=new Set(removed.map(canonical));this.blocks=this.blocks.filter(b=>!names.has(canonical(group(b.header,2))));this.tables=this.tables.filter(r=>r.type!=='BLOCK_RECORD'||!names.has(canonical(group(r,2))));});return removed;}
 exportLibrary(names=this.list().filter(b=>!b.system&&!b.external&&!b.dynamic).map(b=>b.name)){const keys=new Set(names.flatMap(n=>this.dependencyNames(n)).map(canonical));for(const key of keys)this.assertEditable(key);const data={schema:BLOCK_SCHEMA,name:this.name,units:this.units,blocks:this.blocks.filter(b=>keys.has(canonical(group(b.header,2)))).map(x=>clone(x)),tables:this.tables.filter(r=>['LAYER','LTYPE','STYLE','BLOCK_RECORD'].includes(r.type)&& (r.type!=='BLOCK_RECORD'||keys.has(canonical(group(r,2))))).map(x=>clone(x))};if(bytesOf(data)>64*1024*1024)throw new RangeError('A block library export is limited to 64 MiB.');return data;}
 importLibrary(data,{conflict='rename',names=null}={}){validateLibrary(data);if(!['rename','replace','keep'].includes(conflict))throw new RangeError('Choose keep, rename or replace for duplicate definitions.');const imported=clone(data),mapping=new Map(),occupied=new Set(this.blockMap.keys()),source=new Map(imported.blocks.map(b=>[canonical(group(b.header,2)),b])),required=new Set();const stack=names?[...names]:imported.blocks.map(b=>String(group(b.header,2)));while(stack.length){const k=canonical(stack.pop());if(required.has(k))continue;const b=source.get(k);if(!b)throw new Error('Library dependency not found: '+k);required.add(k);for(const r of b.records)if(r.type==='INSERT')stack.push(String(group(r,2)));}
  this.transaction('Import block library',()=>{for(const b of imported.blocks){const original=String(group(b.header,2)),k=canonical(original);if(!required.has(k))continue;let name=original;if(occupied.has(k)&&conflict==='rename'){let i=2;while(occupied.has(canonical(name=original+'_'+i)))i++;}mapping.set(k,name);occupied.add(canonical(name));}
   for(const b of imported.blocks){const original=String(group(b.header,2)),k=canonical(original);if(!required.has(k)||(this.blockMap.has(k)&&conflict==='keep'))continue;const name=mapping.get(k);const rewrite=r=>{r=cleanRecord(r);r=setGroup(r,5,this.nextHandle());if(r.type==='INSERT')r=setGroup(r,2,mapping.get(canonical(group(r,2)))||String(group(r,2)));if(r.attributes)r={...r,attributes:r.attributes.map(a=>setGroup(a,5,this.nextHandle()))};return r;};const oldTable=imported.tables?.find(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===k),existing=this.tables.find(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===canonical(name));let table=existing||this.blockRecord(name,group(oldTable,70,data.units||0));for(const c of [70,280,281])if(oldTable?.groups.some(g=>g.code===c))table=setGroup(table,c,group(oldTable,c));this.tables=this.tables.map(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===canonical(name)?table:r);const header=setGroup(setGroup(setGroup(rewrite(b.header),2,name),3,name),330,group(table,5));const next={header,records:b.records.map(rewrite),end:setGroup(rewrite(b.end||record('ENDBLK')),330,group(table,5))};this.blocks=[...this.blocks.filter(x=>canonical(group(x.header,2))!==canonical(name)),next];}
   for(const type of ['LTYPE','STYLE','LAYER']){const existing=new Set(this.tables.filter(r=>r.type===type).map(r=>canonical(group(r,2,''))));const list=(imported.tables||[]).filter(r=>r.type===type&&!existing.has(canonical(group(r,2,'')))).map(r=>setGroup(cleanRecord(r),5,this.nextHandle()));this.tables=insertTable(this.tables,type,list);}
  });return Object.fromEntries(mapping);}
 /** Replace source records atomically; used by graphical editing and GPU explode. */
 replaceEntities(ids,next,{label='Edit source objects'}={}){validateRecords(next);const wanted=new Set(ids);this.transaction(label,()=>{for(const r of this.entities)if(wanted.has(String(group(r,5)))&&this.layers.find(l=>canonical(l.name)===canonical(group(r,8,'0')))?.locked)throw new Error('Selection contains entities on locked layers.');const stamp=r=>{r=cleanRecord(r);r=setGroup(r,5,this.nextHandle());if(r.attributes)r={...r,attributes:r.attributes.map(stamp)};if(r.vertices)r={...r,vertices:r.vertices.map(stamp)};return r;};this.entities=[...this.entities.filter(r=>!wanted.has(String(group(r,5)))),...next.map(r=>{const n=stamp(r);for(const c of [67,410])if(r.groups.some(g=>g.code===c))n.groups.push({code:c,value:group(r,c)});return n;})];});}
 definitionDrawing(name){const src=this.definition(name),out=BlockDrawing.fromState(this.toState());out.name=name+' · definition';const stamp=r=>{r=setGroup(cleanRecord(r),5,out.nextHandle());if(r.attributes)r={...r,attributes:r.attributes.map(stamp)};if(r.vertices)r={...r,vertices:r.vertices.map(stamp)};return r;};out.entities=src.records.map(r=>{r=stamp(r);r=setGroup(r,67,0);return setGroup(r,410,'Model');});out.ensureHandles();out.refresh();out.undoStack=[];out.redoStack=[];return out;}
 countReferences(){const counts=new Map();const visit=(items,multiplier,path)=>{for(const r of items){if(r.type!=='INSERT')continue;const name=String(group(r,2)),key=canonical(name),options=readInsert(r),number=multiplier*options.rows*options.columns;if(!Number.isSafeInteger(number))throw new RangeError('Expanded block count exceeds safe integer precision.');const placements=(counts.get(key)?.placements||0)+number;if(!Number.isSafeInteger(placements))throw new RangeError('Total expanded block count exceeds safe integer precision.');counts.set(key,{name,placements});if(path.includes(key))throw new Error('Cyclic block graph.');if(path.length>=48)throw new RangeError('Block count nesting exceeds 48.');const b=this.blockMap.get(key);if(b)visit(b.records,number,[...path,key]);}};visit(this.entities,1,[]);return [...counts.values()].sort((a,b)=>a.name.localeCompare(b.name));}
 attributeRows(){const rows=[];for(const r of this.entities){if(r.type!=='INSERT')continue;const o=readInsert(r);for(const a of r.attributes||[])rows.push({handle:String(group(r,5)),block:String(group(r,2)),space:o.space,layer:o.layer,tag:String(group(a,2)),value:String(group(a,1,'')),rows:o.rows,columns:o.columns});}return rows;}
 selectionDocument(ids){const out=BlockDrawing.fromState(this.toState());const wanted=new Set(ids);out.entities=out.entities.filter(r=>wanted.has(String(group(r,5))));out.refresh();return out;}
 previewDocument(name,options={}){const out=new BlockDrawing(null,{name:'Preview · '+name});out.importLibrary(this.exportLibrary([name]),{conflict:'replace'});out.insert(name,options);out.undoStack=[];out.redoStack=[];return out;}
 write(){
  const output=[],emit=(r,owner)=>{r=serializedRecord(r,owner);output.push('0',r.type);for(const g of r.groups){if(typeof g.value==='number'&&!Number.isFinite(g.value))throw new RangeError('Cannot serialize non-finite DXF values.');output.push(String(g.code),String(g.value).replace(/[\r\n]/g,' '));}};
  const existing=new Map(this.sections.map(s=>[s.name,s]));
  const layoutOwners=new Map([...this.layoutBindings()].map(([name,x])=>[name,x.owner]));
  const ownerFor=name=>String(group(this.tables.find(r=>r.type==='BLOCK_RECORD'&&canonical(group(r,2))===canonical(name)),5,''));
  // DXF stores inactive paper spaces in their special BLOCK containers. Merely
  // setting entity group 410/330 inside ENTITIES does not preserve those layouts.
  const rootOwner=r=>{const space=recordSpace(r);return space==='model'?ownerFor('*Model_Space'):layoutOwners.get(canonical(space.replace(/^layout:/,'')))||String(group(r,330,''))||ownerFor('*Paper_Space');};
  const inactive=new Map();for(const b of this.blocks)if(/^[*$]paper_space.+/i.test(String(group(b.header,2,''))))inactive.set(ownerFor(group(b.header,2)),[]);
  const rootEntities=[];for(const r of this.entities){const owner=rootOwner(r),destination=inactive.get(owner);if(destination)destination.push(r);else rootEntities.push(r);}
  const emitEntity=(r,owner)=>{emit(r,owner);if(r.vertices){for(const child of r.vertices)emit(child,String(group(r,5)));emit(r.seqend||record('SEQEND'),String(group(r,5)));}if(r.attributes?.length||group(r,66,0)===1){for(const child of r.attributes||[])emit(child,String(group(r,5)));emit(r.seqend||record('SEQEND'),String(group(r,5)));}};
  const order=['HEADER','CLASSES','TABLES','BLOCKS','ENTITIES','OBJECTS',...this.sections.map(s=>s.name).filter(n=>!['HEADER','CLASSES','TABLES','BLOCKS','ENTITIES','OBJECTS'].includes(n))];
  for(const name of order){const s=existing.get(name);if(!s&&['CLASSES','OBJECTS'].includes(name))continue;
   let header=s?.header||record('SECTION',[[2,name]]);if(name==='HEADER'){
    const groups=header.groups.map(g=>({...g}));let found=false;
    for(let i=0;i<groups.length;i++)if(groups[i].code===9&&groups[i].value==='$ACADVER'&&groups[i+1]){if(!/^AC\d+$/.test(String(groups[i+1].value))||Number(String(groups[i+1].value).slice(2))<1021)groups[i+1].value='AC1021';found=true;}
    if(!found)groups.push({code:9,value:'$ACADVER'},{code:1,value:'AC1021'});
    for(let i=0;i<groups.length;i++)if(groups[i].code===9&&groups[i].value==='$HANDSEED'&&groups[i+1])groups[i+1].value=this.serial.toString(16).toUpperCase();header={...header,groups};
   }
   emit(header);
   if(name==='BLOCKS'){for(const b of this.blocks){const owner=ownerFor(group(b.header,2));emit(b.header,owner);for(const r of b.records)emitEntity(r,owner);for(const r of inactive.get(owner)||[])emitEntity(r,owner);emit(b.end,owner);}}
   else if(name==='ENTITIES')for(const r of rootEntities)emitEntity(r,rootOwner(r));
   else if(name==='TABLES'){let owner='';for(const r of normalizeTables(this.tables)){if(r.type==='TABLE')owner=String(group(r,5,''));emit(r,TABLE_ENTRY_TYPES.has(r.type)?owner:undefined);}}
   else for(const r of s?.records||[])emit(r);
   emit(record('ENDSEC'));
  }emit(record('EOF'));return output.join('\n')+'\n';
 }
 toState(){return {schema:'aperture.block-drawing/1',name:this.name,sections:this.sections,blocks:this.blocks,entities:this.entities,tables:this.tables,serial:this.serial.toString(),revision:this.revision};}
 static fromState(s){if(s?.schema!=='aperture.block-drawing/1'||!Array.isArray(s.entities)||!Array.isArray(s.blocks))throw new Error('Invalid block drawing state.');if(!Array.isArray(s.sections)||!Array.isArray(s.tables)||s.blocks.length>10000||s.entities.length>2000000||!/^\d{1,40}$/.test(String(s.serial)))throw new Error('Invalid persisted block graph.');validateRecords(s.entities);validateRecords(s.tables,{structural:true});for(const b of s.blocks){validateRecords(b.records);validateRecords([b.header,b.end],{structural:true});}const d=new BlockDrawing();for(const key of ['name','sections','blocks','entities','tables'])d[key]=clone(s[key]);d.serial=BigInt(s.serial);d.reserveHandles([...d.entities,...d.blocks.flatMap(b=>[b.header,...b.records,b.end]),...d.tables]);d.revision=Number.isSafeInteger(s.revision)?s.revision:0;d.undoStack=[];d.redoStack=[];d.refresh();d.validateGraph();return d;}
}
function insertTable(records,name,items){if(!items.length)return records;const out=records.slice();const start=out.findIndex(r=>r.type==='TABLE'&&group(r,2)===name);if(start>=0){const end=out.findIndex((r,i)=>i>start&&r.type==='ENDTAB');out.splice(end<0?out.length:end,0,...items);}else out.push(record('TABLE',[[2,name],[70,items.length]]),...items,record('ENDTAB'));return out;}
function normalizeTables(items){const out=items.slice();for(let i=0;i<out.length;i++)if(out[i].type==='TABLE'){let end=i+1;while(end<out.length&&out[end].type!=='ENDTAB')end++;out[i]=setGroup(out[i],70,end-i-1);}return out;}
export function validateRecords(items,{structural=false}={}){if(!Array.isArray(items)||items.length>1000000)throw new RangeError('Invalid block entity list.');let words=0;const visit=(r,depth)=>{if(depth>8||!r||typeof r.type!=='string'||!/^[A-Z][A-Z0-9_]*$/.test(r.type)||(!structural&&['SECTION','ENDSEC','BLOCK','ENDBLK','EOF','TABLE','ENDTAB'].includes(r.type))||!Array.isArray(r.groups))throw new Error('Invalid block entity record.');for(const g of r.groups){if(++words>2000000||!Number.isInteger(g.code)||g.code<1||g.code>1071||!['number','string'].includes(typeof g.value)||(typeof g.value==='number'&&!Number.isFinite(g.value)))throw new Error('Invalid DXF group in block record.');}for(const key of ['attributes','vertices'])if(r[key]){if(!Array.isArray(r[key]))throw new Error('Invalid child entity array.');for(const child of r[key])visit(child,depth+1);}};for(const r of items)visit(r,0);}
export function validateLibrary(data){if(!data||data.schema!==BLOCK_SCHEMA||!Array.isArray(data.blocks)||data.blocks.length>10000||!Array.isArray(data.tables)||data.tables.length>100000)throw new Error('Invalid or excessive Aperture block library.');if(bytesOf(data)>64*1024*1024)throw new RangeError('Library exceeds the 64 MiB limit.');validateRecords(data.tables);const names=new Set();for(const b of data.blocks){if(b.header?.type!=='BLOCK'||!Array.isArray(b.header.groups))throw new Error('Invalid BLOCK header.');const name=validateName(group(b.header,2,''),{anonymous:true}),key=canonical(name);if(names.has(key))throw new Error('Duplicate library definition: '+name);names.add(key);validateRecords(b.records);validateRecords([b.header,...(b.end?[b.end]:[])],{structural:true});if(/^[*$](model_space|paper_space)/i.test(name))throw new Error('Library cannot redefine a model/paper space container.');}}

const TABLE_ENTRY_TYPES=new Set(['LAYER','LTYPE','STYLE','BLOCK_RECORD','APPID','VIEW','VPORT','UCS','DIMSTYLE']);
