/** GPU results -> standard DXF records. This module formats returned coordinates;
 * it does not evaluate block matrices, tessellate curves or rasterize geometry. */
import { group,record,readInsert,canonical } from './document.js';
import { decodeDxfText } from '../dxf/index.js';
const RAD=180/Math.PI;
export function validateExplodable(d,ids){const known=new Set(['LINE','CIRCLE','ARC','ELLIPSE','LWPOLYLINE','POLYLINE','SPLINE','SOLID','TRACE','POINT','XLINE','RAY','TEXT','MTEXT','INSERT','ATTDEF','ATTRIB']);const visit=(items,path=[])=>{for(const r of items){if(!known.has(r.type))throw new Error('GPU explode does not support '+r.type+' in this exact 2D conversion profile.');if(r.groups.some(g=>[30,31,32,33,38,210,220].includes(g.code)&&Number(g.value)!==0))throw new Error('GPU explode is restricted to planar XY source geometry. Nonplanar coordinates are preserved by keeping the INSERT.');if(r.type==='INSERT'){const name=String(group(r,2)),m=d.assertEditable(name);if(!m.allowExplode)throw new Error(name+' disallows explode.');if(path.includes(canonical(name)))throw new Error('Cyclic block reference.');if(m.base[2]!==0)throw new Error('A nonzero block-base Z is outside the planar explode profile.');visit(d.definition(name).records,[...path,canonical(name)]);if(r.attributes)visit(r.attributes,path);}}};const roots=ids.map(id=>d.entityMap.get(id));if(roots.some(r=>r?.type!=='INSERT'))throw new Error('Explode requires root INSERT references.');visit(roots);return roots;}
export function sourceByHandle(d){const map=new Map(),visit=r=>{const h=String(group(r,5,''));if(h)map.set(h,r);r.attributes?.forEach(visit);r.vertices?.forEach(visit);};d.entities.forEach(visit);d.blocks.forEach(b=>b.records.forEach(visit));return map;}
export function explodedRecords(pages,{drawing,layers,space='model',keepAttributes=true}={}){const source=sourceByHandle(drawing),out=[];for(const page of pages){const f=new Float32Array(page.entities),u=new Uint32Array(page.entities),af=new Float32Array(page.aux),au=new Uint32Array(page.aux);for(let i=0;i<page.count;i++){const j=i*32,type=u[j+16],r=source.get(String(page.handles[i]||''));if(r?.type==='ATTRIB'&&!keepAttributes)continue;const x=f[j]+f[j+2],y=f[j+1]+f[j+3],layer=layers[u[j+18]],packed=u[j+17]||layer?.color||0xffffffff,common=[[8,layer?.name||'0'],[420,((packed&255)<<16)|(packed&65280)|((packed>>>16)&255)],[67,space==='model'?0:1],[410,space==='model'?'Model':space.replace(/^layout:/,'')]],point=(code,dx=0,dy=0)=>[[code,x+dx],[code+10,y+dy],[code+20,0]];let result;
 if(type===1)result=record('LINE',[...common,...point(10),...point(11,f[j+4],f[j+5])]);
 else if(type===2)result=record('ELLIPSE',[...common,...point(10),[11,f[j+4]],[21,f[j+5]],[31,0],[40,f[j+6]],[41,f[j+8]],[42,f[j+8]+f[j+9]]]);
 else if(type===3||type===8){const n=u[j+21],o=u[j+20],pairs=[...common,[90,n],[70,(u[j+23]&1)?1:0]];for(let k=0;k<n;k++)pairs.push([10,x+af[o+k*4]],[20,y+af[o+k*4+1]],[42,af[o+k*4+2]]);result=record('LWPOLYLINE',pairs);}
 else if(type===4){if(!r)throw new Error('Cannot recover the source text for exploded entity #'+u[j+19]);const value=decodeDxfText(r.groups.filter(g=>g.code===3||g.code===1).map(g=>g.value).join(''),r.type==='MTEXT');if(/[\r\n]/.test(value))throw new Error('Multiline text is outside the exact explode text profile.');result=record('TEXT',[...common,...point(10),...point(11),[1,value],[40,f[j+4]],[41,f[j+5]],[50,f[j+6]*RAD],[51,f[j+7]*RAD],[71,(u[j+23]&64)?4:0],[72,f[j+10]],[73,f[j+11]],[7,String(group(r,7,'STANDARD'))]]);}
 else if(type===5)result=record('SOLID',[...common,...point(10),...point(11,f[j+4],f[j+5]),...point(12,f[j+6],f[j+7]),...point(13,f[j+6],f[j+7])]);
 else if(type===6){const o=u[j+20],degree=au[o],knots=au[o+1],n=au[o+2],pairs=[...common,[70,4],[71,degree],[72,knots],[73,n],[74,0]];for(let k=0;k<knots;k++)pairs.push([40,af[o+4+k]]);const start=o+4+knots;for(let k=0;k<n;k++)pairs.push([41,af[start+k*4+2]],...point(10,af[start+k*4],af[start+k*4+1]));result=record('SPLINE',pairs);}
 else if(type===7)result=record('POINT',[...common,...point(10)]);
 else if(type===9||type===10)result=record(type===9?'XLINE':'RAY',[...common,...point(10),[11,f[j+4]],[21,f[j+5]],[31,0]]);
 else throw new Error('Unsupported GPU explode result type '+type);out.push(result);
 }}return out;}
