import { BlockStudio } from './block-studio.js';
import { validateExplodable, explodedRecords } from '../blocks/explode.js';
/** Static DXF BLOCK/INSERT workbench. UI owns no CAD rasterization path. */
import { BlockDrawing, UNIT_NAMES, group, record, recordSpace, readInsert, unitFactor, canonical } from '../blocks/document.js';
import { BlockShelf, engineeringLibrary, blockSampleDxf } from '../blocks/library.js';
import { placementPreview, ownerOf } from '../blocks/preview.js';
import { DxfWorkerClient } from '../dxf/client.js';
import { ComputeCad } from '../gpu/index.js';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(name,label,value=0,attrs='')=>`<label>${label}<input name="${name}" type="number" value="${Number(value)}" step="any" required ${attrs}></label>`;
const check=(name,label,on=false)=>`<label class="block-check"><input name="${name}" type="checkbox" ${on?'checked':''}>${label}</label>`;
const units=(name,value)=>`<label>Insertion units<select name="${name}">${UNIT_NAMES.map((s,i)=>`<option value="${i}" ${i===value?'selected':''}>${s}</option>`).join('')}</select></label>`;
const button=(id,label,cls='')=>`<button type="button" id="${id}" class="button small ${cls}">${label}</button>`;
const encode=s=>new TextEncoder().encode(s).buffer;
const numeric=(form,name)=>Number(form.elements.namedItem(name).value);
const checked=(form,name)=>!!form.elements.namedItem(name)?.checked;
const text=(form,name)=>String(form.elements.namedItem(name)?.value||'');
const keyOf=(library,name)=>library+'\0'+canonical(name);
export class BlockWorkbench {
 constructor(host){
  this.h=host;this.shelf=new BlockShelf();this.shelf.add(engineeringLibrary());this.activeSource='drawing';this.filter='';this.selected=null;this.selection=new Set();this.docId=null;this.opened=false;this.placement=null;this.previewSerial=0;this.placementSerial=0;this.previewDevice=null;this.previewQueue=Promise.resolve();this.previewImporter=new DxfWorkerClient();this.placementImporter=new DxfWorkerClient();this.selectionFocus=false;this.lastInsert=null;
  this.root=$('blocks-panel');this.root.innerHTML=`<div class="block-panel-head"><div><span class="eyebrow">REUSABLE GEOMETRY</span><h2>Blocks</h2></div><button id="blocks-close" class="icon-button" aria-label="Close block palette">×</button></div>
   <div class="block-actions">${button('block-new','New drawing')}${button('block-workshop','Workshop')}${button('block-create','Create block')}${button('block-import','Import library')}</div>
   <div class="block-source-tabs" role="tablist" aria-label="Block sources">${[['drawing','Drawing'],['libraries','Libraries'],['recent','Recent'],['favorites','Favorites']].map(([id,label])=>`<button data-block-source="${id}" role="tab" aria-selected="${id==='drawing'}">${label}</button>`).join('')}</div>
   <div class="block-search"><input id="block-search" class="search-input" type="search" placeholder="Search blocks, tags, description…" aria-label="Search blocks"><select id="block-library-select" aria-label="Library selection"></select></div>
   <div class="block-countline"><span id="block-count">0 blocks</span><button class="text-button" id="block-refresh">Refresh drawing</button></div><div id="block-list" class="block-list" role="listbox" aria-label="Block definitions"></div>
   <section class="block-preview"><canvas id="block-preview-canvas" aria-label="Selected block preview, WebGPU compute only"></canvas><span id="block-preview-state">Select a block</span><span class="block-preview-chip">COMPUTE</span></section>
   <section id="block-details" class="block-details"><p>Select a reusable definition to inspect its attributes and nested references.</p></section>
   <div class="block-selection-bar"><span id="block-selection-count">No source selection</span>${button('block-selected-properties','Properties')}${button('block-show-tree','Show in tree')}</div>
   <div class="block-footer">${button('block-undo','Undo block edit')}${button('block-redo','Redo')}${button('block-purge','Purge')}${button('block-commands','All block tools')}${button('block-export-drawing','Save edited DXF')}${button('block-save-shelf','Save libraries locally')}${button('block-load-shelf','Restore libraries')}</div>
   <input id="block-library-file" type="file" accept=".dxf,.json" multiple hidden>`;
  $('blocks-close').onclick=()=>this.close();$('blocks-open').onclick=()=>this.h.run(()=>this.open());
  $('block-new').onclick=()=>this.h.run(()=>this.newDrawing(false));$('block-workshop').onclick=()=>this.h.run(()=>this.newDrawing(true));$('block-create').onclick=()=>this.h.run(()=>this.createDialog());
  $('block-import').onclick=()=>$('block-library-file').click();$('block-library-file').onchange=e=>this.h.run(async()=>{for(const file of e.target.files)await this.importLibraryFile(file);e.target.value='';});
  $('block-search').oninput=e=>{this.filter=e.target.value;this.renderList();};$('block-library-select').onchange=()=>this.renderList();
  this.root.querySelectorAll('[data-block-source]').forEach(b=>b.onclick=()=>{this.activeSource=b.dataset.blockSource;this.renderList();});
  $('block-refresh').onclick=()=>this.h.run(async()=>{await this.ensureDrawing(false);this.render();});
  $('block-selected-properties').onclick=()=>this.h.run(()=>this.referenceDialog());$('block-show-tree').onclick=()=>this.h.run(()=>this.showSelectionTree());
  $('block-undo').onclick=()=>this.h.run(()=>this.history(false));$('block-redo').onclick=()=>this.h.run(()=>this.history(true));
  $('block-commands').onclick=()=>this.commandDialog();
  $('block-purge').onclick=()=>this.h.run(()=>this.purge());$('block-export-drawing').onclick=()=>this.h.run(()=>this.exportDrawing());
  $('block-save-shelf').onclick=()=>this.h.run(async()=>{await this.shelf.save();this.h.toast('Libraries, favorites and recent blocks saved in this browser.');});
  $('block-load-shelf').onclick=()=>this.h.run(async()=>{if(await this.shelf.load()){this.selected=null;this.render();this.h.toast('Browser-local block libraries restored.');}else this.h.toast('No saved block library was found.');});
  this.root.addEventListener('keydown',e=>{if(e.key==='Escape'){this.cancel();e.stopPropagation();}});
  const list=$('block-list');list.addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp','Home','End','Enter'].includes(e.key))return;const items=[...list.querySelectorAll('[data-block-key]')],at=items.indexOf(document.activeElement);if(e.key==='Enter'){document.activeElement?.click();if(this.selected)this.h.run(()=>this.insertDialog());}else {e.preventDefault();const i=e.key==='Home'?0:e.key==='End'?items.length-1:Math.max(0,Math.min(items.length-1,at+(e.key==='ArrowUp'?-1:1)));items[i]?.focus();items[i]?.click();}});
  this.h.canvas.addEventListener('dblclick',()=>{if(this.selection.size===1&&!this.placement)this.h.run(()=>this.referenceDialog());});
  this.h.canvas.addEventListener('dragover',e=>{if(e.dataTransfer.types.includes('application/x-aperture-block')){e.preventDefault();e.dataTransfer.dropEffect='copy';e.stopPropagation();}});
  this.h.canvas.addEventListener('drop',e=>{const value=e.dataTransfer.getData('application/x-aperture-block');if(!value)return;e.preventDefault();e.stopPropagation();this.h.run(async()=>{const k=JSON.parse(value),entry=this.entries().find(x=>x.library===k.library&&x.meta.name===k.name);if(!entry)throw new Error('The dragged definition is no longer available.');await this.select(entry);this.insertDialog(null,this.point(e));});});
 }
 get drawing(){return this.h.current()?.blockDrawing||null;}
 get engine(){return this.h.engine;}
 get font(){return this.h.font();}
 get doc(){return this.h.current();}
 async open(){this.opened=true;document.body.classList.add('blocks-open');this.root.hidden=false;this.h.engine.requestFrame();await this.ensureDrawing(false);this.render();$('block-search').focus();}
 close(){this.opened=false;document.body.classList.remove('blocks-open');this.root.hidden=true;this.previewSerial++;this.previewImporter.cancel();this.previewDevice?.dispose();this.previewDevice=null;this.h.engine.requestFrame();}
 async ensureDrawing(create=false){
  if(this.drawing){if(!this.doc.blockPrepared)await this.h.prepare(this.drawing);return this.drawing;}
  const doc=this.doc;
  if(doc?.sourceFile){const id=doc.id,source=await doc.sourceFile.arrayBuffer(),d=new BlockDrawing(source,{name:doc.name});if(this.doc?.id!==id)throw new Error('The active document changed.');doc.blockDrawing=d;this.docId=id;await this.h.prepare(d);return d;}
  if(create){await this.newDrawing(false);return this.drawing;}
  return null;
 }
 async newDrawing(sample=false){await this.cancel();const d=sample?new BlockDrawing(blockSampleDxf(),{name:'Block workshop.dxf'}):new BlockDrawing(null,{name:'Untitled blocks.dxf'});await this.h.openDrawing(d);this.docId=this.doc.id;this.selection.clear();this.activeSource=sample?'drawing':'libraries';this.selected=null;this.render();this.h.toast(sample?'Block workshop opened. Double-click a definition to insert it.':'New editable drawing opened; the previous tab was kept.');}
 onDocument(){if(this.docId!==this.doc?.id||this.spaceId!==this.doc?.activeSpace){this.spaceId=this.doc?.activeSpace;this.docId=this.doc?.id;this.selection.clear();this.selected=null;this.previewSerial++;}if(this.opened){this.h.run(async()=>{await this.ensureDrawing(false);this.render();});}this.renderSelection();}
 entries(){const entries=[];const d=this.drawing;if(d)for(const meta of d.list())entries.push({library:'drawing',libraryName:'Current drawing',meta,drawing:d});for(const lib of this.shelf.libraries){if(!lib.drawing)lib.drawing=(()=>{const d=new BlockDrawing();d.importLibrary(lib.data,{conflict:'replace'});d.undoStack=[];return d;})();for(const meta of lib.drawing.list())entries.push({library:lib.id,libraryName:lib.name,meta,drawing:lib.drawing});}return entries;}
 render(){const select=$('block-library-select'),previous=select.value;select.replaceChildren(new Option('All libraries',''));for(const l of this.shelf.libraries)select.add(new Option(l.name,l.id));select.value=previous;this.renderList();this.renderSelection();if(this.selected){const fresh=this.entries().find(x=>keyOf(x.library,x.meta.name)===keyOf(this.selected.library,this.selected.meta.name));if(fresh){this.selected=fresh;this.renderDetails();}else this.selected=null;}}
 renderList(){const all=this.entries(),query=this.filter.toLocaleLowerCase(),source=this.activeSource,library=$('block-library-select').value;let entries=all.filter(e=>source==='drawing'?e.library==='drawing':source==='libraries'?e.library!=='drawing'&&(!library||library===e.library):source==='favorites'?this.shelf.favorites.has(this.shelf.key(e.library,e.meta.name)):this.shelf.recent.some(r=>keyOf(r.library,r.name)===keyOf(e.library,e.meta.name)));
  if(source==='recent')entries.sort((a,b)=>this.shelf.recent.findIndex(r=>keyOf(r.library,r.name)===keyOf(a.library,a.meta.name))-this.shelf.recent.findIndex(r=>keyOf(r.library,r.name)===keyOf(b.library,b.meta.name)));
  else entries.sort((a,b)=>a.meta.name.localeCompare(b.meta.name));
  entries=entries.filter(e=>(e.meta.name+' '+e.meta.description+' '+e.meta.attributes.map(a=>a.tag).join(' ')).toLocaleLowerCase().includes(query));
  this.root.querySelectorAll('[data-block-source]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.blockSource===source)));$('block-library-select').hidden=source!=='libraries';$('block-count').textContent=entries.length+' definitions';
  const list=$('block-list');list.replaceChildren();const limit=500;
  for(const entry of entries.slice(0,limit)){const b=document.createElement('button');b.type='button';b.className='block-tile';b.dataset.blockKey=keyOf(entry.library,entry.meta.name);b.role='option';b.draggable=!entry.meta.external;b.setAttribute('aria-selected',String(this.selected&&keyOf(this.selected.library,this.selected.meta.name)===b.dataset.blockKey));b.title=entry.meta.description||entry.meta.name;
   b.innerHTML=`<span class="block-symbol">${entry.meta.external?'↗':entry.meta.dependencies.length?'▱':'◇'}</span><span class="block-tile-copy"><strong>${esc(entry.meta.name)}</strong><small>${esc(entry.meta.description||entry.libraryName)}</small><em>${entry.meta.count} records · ${entry.meta.attributes.length} attributes${entry.meta.dependencies.length?' · '+entry.meta.dependencies.length+' nested':''}</em></span><span class="block-fav">${this.shelf.favorites.has(this.shelf.key(entry.library,entry.meta.name))?'★':''}</span>`;
   b.onclick=()=>this.h.run(()=>this.select(entry));b.ondblclick=()=>this.h.run(async()=>{await this.select(entry,false);await this.insertDialog();});b.ondragstart=e=>e.dataTransfer.setData('application/x-aperture-block',JSON.stringify({library:entry.library,name:entry.meta.name}));list.append(b);
  }
  if(!entries.length){const p=document.createElement('p');p.className='block-empty';p.textContent=source==='drawing'&&!this.drawing?'Open a DXF or create a block drawing. The Libraries tab contains 14 original engineering definitions.':'No matching block definitions.';list.append(p);}
  if(entries.length>limit){const p=document.createElement('p');p.className='block-empty';p.textContent='Showing the first 500 matches. Refine the search to inspect any definition.';list.append(p);}
 }
 async select(entry,preview=true){this.selected=entry;this.renderList();this.renderDetails();if(preview)this.queueThumbnail(entry);}
 renderDetails(){const entry=this.selected;if(!entry)return;const m=entry.meta,root=$('block-details');root.innerHTML=`<div class="block-detail-title"><strong>${esc(m.name)}</strong><button id="block-favorite" class="icon-button" aria-label="Toggle favorite">${this.shelf.favorites.has(this.shelf.key(entry.library,m.name))?'★':'☆'}</button></div><p>${esc(m.description||entry.libraryName)}</p><div class="block-meta"><span>Base point</span><strong>${m.base.map(x=>Number(x).toLocaleString()).join(', ')}</strong><span>Units</span><strong>${esc(UNIT_NAMES[m.units]||'Unknown')}</strong><span>Dependencies</span><strong>${m.dependencies.length}</strong></div><div class="block-detail-actions">${button('block-insert','Insert…','primary')}${button('block-tree','Definition tree')}${button('block-export-one','Export block')}${entry.library==='drawing'?button('block-studio','Block Studio')+button('block-definition','Definition properties')+button('block-attributes','Attribute definitions')+button('block-refs','References'):button('block-adopt','Add to drawing')}</div>${m.dynamic?'<p class="block-warning">Potential dynamic/evaluated definition. Existing static geometry is viewable; editing requires a static export from the source CAD system.</p>':''}${m.external?'<p class="block-warning">External reference: listed for inspection, not bound or resolved by this application.</p>':''}`;
  $('block-favorite').onclick=()=>{this.shelf.favorite(entry.library,m.name);this.renderList();this.renderDetails();};$('block-insert').disabled=m.external||m.dynamic;$('block-insert').onclick=()=>this.h.run(()=>this.insertDialog());$('block-tree').onclick=()=>this.treeDialog(entry);$('block-export-one').onclick=()=>this.exportLibrary(entry);$('block-studio')?.addEventListener('click',()=>this.h.run(()=>this.openStudio()));$('block-definition')?.addEventListener('click',()=>this.h.run(()=>this.definitionDialog()));$('block-attributes')?.addEventListener('click',()=>this.h.run(()=>this.attributesDialog()));$('block-refs')?.addEventListener('click',()=>this.referencesDialog(m.name));$('block-adopt')?.addEventListener('click',()=>this.h.run(()=>this.adopt(entry)));
 }
 queueThumbnail(entry){const serial=++this.previewSerial;this.previewImporter.cancel();$('block-preview-state').textContent='Preparing compute preview…';this.previewQueue=this.previewQueue.catch(()=>{}).then(async()=>{
   if(serial!==this.previewSerial||!this.opened)return;
   try{if(entry.meta.external)throw new Error('External reference has no bound preview.');const source=entry.drawing.previewDocument(entry.meta.name,{attributes:Object.fromEntries(entry.meta.attributes.map(a=>[a.tag,a.value]))});const model=await this.previewImporter.parse(encode(source.write()),this.font,{name:entry.meta.name,document:true});if(serial!==this.previewSerial||!this.opened)return;
    if(!this.previewDevice){const engine=new ComputeCad($('block-preview-canvas'),{memoryBudget:128*1024*1024,maxPixels:320*200,pixelRatio:1});this.previewDevice=engine;try{await engine.initialize(this.font);}catch(error){engine.dispose();if(this.previewDevice===engine)this.previewDevice=null;throw error;}}
    if(serial!==this.previewSerial||!this.opened)return;const preview=this.previewDevice;if(preview.font!==this.font)await preview.setFont(this.font);await preview.setModel(model);preview.flags=0;preview.fit();preview.requestFrame();$('block-preview-state').textContent=model.count+' entities · GPU preview';
   }catch(error){if(serial!==this.previewSerial||error.name==='AbortError')return;$('block-preview-state').textContent=error.message;}
  });}
 async adopt(entry,conflict='rename'){const d=await this.ensureDrawing(true);let mapping;await this.change(()=>{mapping=d.importLibrary(entry.drawing.exportLibrary([entry.meta.name]),{conflict});});const name=mapping[entry.meta.name]||entry.meta.name;this.selected=this.entries().find(e=>e.library==='drawing'&&e.meta.name===name);this.activeSource='drawing';this.render();return name;}
 async importLibraryFile(file){if(file.size>64*1024*1024)throw new RangeError('A block library is limited to 64 MiB.');let data;if(/\.dxf$/i.test(file.name)){const d=new BlockDrawing(await file.arrayBuffer(),{name:file.name});if(!d.list().length&&d.entities.length){d.create(file.name.replace(/\.dxf$/i,''),d.entities.map(r=>String(group(r,5))),[0,0,0],{mode:'delete'});}data=d.exportLibrary();}else data=JSON.parse(await file.text());data={...data,name:file.name};const id=this.shelf.add(data);this.activeSource='libraries';this.render();$('block-library-select').value=id;this.renderList();this.h.toast('Imported '+data.blocks.length+' definitions locally; dependencies retained.');}
 exportLibrary(entry=this.selected){if(!entry)return;const data=entry.drawing.exportLibrary([entry.meta.name]);this.h.dialog('Export '+entry.meta.name,`<p class="dialog-intro">Includes the definition, all nested dependencies, and supported layer, linetype and text-style tables.</p><div class="block-detail-actions">${button('block-json-export','Block library · JSON','primary')}${button('block-dxf-export','Block library · DXF')}</div>`,'BLOCK LIBRARY / EXPORT');$('block-json-export').onclick=()=>this.h.download(data,entry.meta.name+'.blocks.json');$('block-dxf-export').onclick=()=>{const d=new BlockDrawing(null,{name:entry.meta.name});d.importLibrary(data,{conflict:'replace'});this.h.download(d.write(),entry.meta.name+'.dxf','application/dxf');};}
 async exportDrawing(){const d=await this.ensureDrawing(false);if(!d)throw new Error('Open an editable DXF drawing first.');this.h.download(d.write(),d.name.replace(/\.dxf$/i,'')+'-edited.dxf','application/dxf');this.h.toast('Editable BLOCK, INSERT, attributes and drawing entities exported. The imported source is still unchanged.');}
 async change(action,{history=false}={}){const id=this.doc?.id;if(!id)throw new Error('No active drawing.');return this.h.enqueue(async()=>{
   if(this.doc?.id!==id)throw new Error('The active drawing changed before the block command started.');await this.cancel();const d=this.drawing;if(!d)throw new Error('No editable source graph.');const before=d.snapshot(),undo=d.undoStack.slice(),redo=d.redoStack.slice(),revision=d.revision;
   try{const value=history?await action(d):d.transaction('Block command',()=>action(d));if(d.revision===revision)return value;await this.h.commit(d);this.selection.clear();this.render();return value;}
   catch(error){d.restore(before);d.undoStack=undo;d.redoStack=redo;d.revision=revision;throw error;}
  });}
 async history(redo){await this.ensureDrawing(false);if(!this.drawing)return;let label;await this.change(d=>{label=redo?d.redo():d.undo();},{history:true});if(label)this.h.toast((redo?'Redid ':'Undid ')+label);}
 async purge(){const d=await this.ensureDrawing(false);if(!d)return;const copy=BlockDrawing.fromState(d.toState()),names=copy.purge();if(!names.length){this.h.toast('No unreferenced block definitions.');return;}this.h.dialog('Purge unused definitions',`<p class="dialog-intro">${names.length} unreachable definitions will be removed. Nested blocks referenced by live INSERTs or dimension pictures are retained. This command is undoable.</p><div class="block-record-list">${names.map(n=>`<div>${esc(n)}</div>`).join('')}</div>${button('block-purge-confirm','Purge '+names.length+' blocks','primary')}`,'BLOCK LIBRARY / PURGE');$('block-purge-confirm').onclick=()=>this.h.run(async()=>{this.h.closeDialog();await this.change(d=>d.purge());this.selected=null;this.render();});}
 selectEntity(id,{add=false}={}){const mapped=ownerOf(this.engine.model,id),raw=this.engine.describe(id),source=raw?.handle?this.drawing?.entityMap.get(String(raw.handle)):null,root=mapped||(source?{handle:String(raw.handle),type:source.type,block:null}:null);if(!add)this.selection.clear();if(root){if(!mapped){this.primitiveSelections??=new Map();this.primitiveSelections.set(root.handle,{first:id,count:1});}this.selection.has(root.handle)&&add?this.selection.delete(root.handle):this.selection.add(root.handle);this.selectionFocus=true;}this.renderSelection();return root;}
 renderSelection(){const d=this.drawing;for(const id of this.selection)if(d&&!d.entityMap.has(id))this.selection.delete(id);$('block-selection-count').textContent=this.selection.size?this.selection.size+' source object'+(this.selection.size===1?'':'s')+' selected':'Shift-click to select source objects';$('block-undo').disabled=!d?.undoStack.length;$('block-redo').disabled=!d?.redoStack.length;if(this.engine.model&&!this.engine.preparing&&this.engine.selectEntities){this.engine.selectEntities(this.selectedRanges());}}
 async showSelectionTree(){await this.ensureDrawing(false);const r=this.drawing?.entityMap.get([...this.selection][0]);if(r?.type==='INSERT'){const name=String(group(r,2));const entry=this.entries().find(e=>e.library==='drawing'&&canonical(e.meta.name)===canonical(name));if(entry){await this.select(entry,false);this.treeDialog(entry,String(group(r,5)));}}else if(this.selected)this.treeDialog(this.selected);else this.h.toast('Select a block reference or a library definition first.');}
 treeDialog(entry,highlight=null){const tree=entry.drawing.tree(entry.meta.name),render=(n,level=0)=>`<details class="block-tree-node" ${level<2?'open':''}><summary><span>${esc(n.name)}</span>${n.handle?`<small>#${esc(n.handle)} · layer ${esc(n.layer)}</small>`:'<small>DEFINITION</small>'}</summary>${n.missing?'<p class="block-warning">Missing definition</p>':n.cycle?'<p class="block-warning">Cyclic reference rejected</p>':n.truncated?'<p class="block-warning">Tree expansion safety limit; inspect this definition separately.</p>':`<p>${n.entities} direct records${n.options?' · rotation '+n.options.rotation+'° · scale '+n.options.scale.join(', ')+' · '+n.options.rows+' × '+n.options.columns+' array':''}</p>${n.children.map(c=>render(c,level+1)).join('')}`}</details>`;
  this.h.dialog(entry.meta.name+' / definition tree',`<p class="dialog-intro">${highlight?'Selected root INSERT #'+esc(highlight)+'. ':''}Nested references retain their block name, handle, layer, base point and transform. A definition can be shared by many placements.</p><div class="block-tree">${render(tree)}</div>`,'BLOCKS / SHOW IN TREE');}
 referencesDialog(name=null){const d=this.drawing;if(!d)return;const refs=d.references(name);this.h.dialog(name?name+' / references':'All INSERT references',`<p class="dialog-intro">${refs.length} INSERT records${refs.length>5000?' (first 5,000 shown)':''}${name?' referencing this definition':''}. Nested rows describe references inside a definition, not flattened GPU copies.</p><div class="block-record-list">${refs.slice(0,5000).map(r=>`<button class="block-reference-row" data-reference="${esc(r.id)}" data-parent="${esc(r.parent||'')}"><strong>${esc(r.name)}</strong><span>#${esc(r.id)} · ${esc(r.parent?'in '+r.parent:r.options.space)} · layer ${esc(r.layer)}</span><small>XYZ ${r.options.position.join(', ')} · rotation ${r.options.rotation}° · scale ${r.options.scale.join(', ')} · ${r.options.rows} × ${r.options.columns}</small></button>`).join('')||'<p>No references.</p>'}</div>`,'BLOCKS / INSERT GRAPH');document.querySelectorAll('[data-reference]').forEach(b=>b.onclick=()=>this.h.run(async()=>{if(b.dataset.parent){this.treeDialog({drawing:d,meta:d.metadata(b.dataset.parent)});return;}this.selection=new Set([b.dataset.reference]);this.h.closeDialog();await this.referenceDialog();}));}
 async insertDialog(reference=null,point=null){const d=await this.ensureDrawing(true);let entry=this.selected;if(reference){const r=d.entityMap.get(reference);if(r?.type!=='INSERT')throw new Error('Select a root INSERT reference.');entry={library:'drawing',libraryName:'Current drawing',drawing:d,meta:d.metadata(String(group(r,2)))};}if(!entry)throw new Error('Select a block definition.');if(entry.meta.external)throw new Error('Bind external references in their source CAD system before inserting.');
  const m=entry.meta,existing=reference?readInsert(d.entityMap.get(reference)):null,u=reference?1:unitFactor(m.units,d.units),o=existing||{position:point||[0,0,0],scale:[u,u,u],rotation:0,rows:1,columns:1,rowSpacing:20,columnSpacing:20,layer:d.layers.find(l=>!l.locked)?.name||'0',attributes:Object.fromEntries(m.attributes.map(a=>[a.tag,a.value]))};
  const id=this.doc.id,source=entry.library==='drawing'?'Current drawing':entry.libraryName;
  this.h.dialog(reference?'Edit INSERT · '+m.name:'Insert · '+m.name,`<form id="block-insert-form" class="block-form"><p class="dialog-intro">${esc(source)} · ${esc(UNIT_NAMES[m.units])} → ${esc(UNIT_NAMES[d.units])}${!reference?' · unit factor '+u:''}. Geometry and nested transforms are prepared and drawn on the GPU.</p><div class="block-form-grid">${field('x','Insertion X',o.position[0])}${field('y','Insertion Y',o.position[1])}${field('z','Insertion Z',o.position[2])}${field('sx','Scale X',o.scale[0])}${field('sy','Scale Y',o.scale[1])}${field('sz','Scale Z',o.scale[2])}${field('rotation','Rotation · degrees',o.rotation)}<label>Insertion layer<select name="layer">${d.layers.map(l=>`<option value="${esc(l.name)}" ${l.name===o.layer?'selected':''} ${l.locked?'disabled':''}>${esc(l.name)}${l.locked?' · locked':''}</option>`).join('')}</select></label>${!reference&&entry.library!=='drawing'?'<label>Name conflict<select name="conflict"><option value="rename">Import with unique name</option><option value="keep">Use existing definition</option><option value="replace">Redefine existing definition</option></select></label>':''}</div><details class="block-form-section" ${o.rows*o.columns>1?'open':''}><summary>Rectangular INSERT array</summary><div class="block-form-grid">${field('rows','Rows',o.rows,'min="1" max="32767"')}${field('columns','Columns',o.columns,'min="1" max="32767"')}${field('rowSpacing','Row spacing',o.rowSpacing)}${field('columnSpacing','Column spacing',o.columnSpacing)}</div><p>Spacing is measured along the rotated array axes, independently of block scale.</p></details><details class="block-form-section" open><summary>Attributes · ${m.attributes.length}</summary><div class="block-attribute-fields">${m.attributes.map((a,i)=>`<label>${esc(a.prompt||a.tag)} <small>${esc(a.tag)}${a.invisible?' · invisible':''}${a.constant?' · constant':''}${a.verify?' · verify':''}</small><input name="attribute${i}" value="${esc(o.attributes[a.tag]??a.value)}" ${a.constant?'readonly':''} maxlength="16384"></label>`).join('')||'<p>This definition has no attribute templates.</p>'}</div></details>${!reference?`<div class="block-placement-options">${check('screen','Specify position on screen',!point)}${check('rotateScreen','Specify angle on screen')}${check('scaleScreen','Specify uniform scale on screen')}${check('repeat','Repeat insertion')}${check('objectSnap','GPU object snap',true)}<label>Grid snap interval<input type="number" name="snap" value="0" min="0" step="any"></label></div>`:''}<div class="block-form-actions">${reference?button('block-delete-reference','Delete reference')+button('block-replace-reference','Replace with selected block'):button('block-mirror-x','Mirror X')+button('block-mirror-y','Mirror Y')}<span></span><button type="submit" class="button primary">${reference?'Apply INSERT changes':'Insert block'}</button></div></form>`,'BLOCK / '+(reference?'REFERENCE PROPERTIES':'INSERT'));
  const form=$('block-insert-form');$('block-mirror-x')?.addEventListener('click',()=>form.elements.sx.value=-numeric(form,'sx'));$('block-mirror-y')?.addEventListener('click',()=>form.elements.sy.value=-numeric(form,'sy'));
  if(reference){$('block-delete-reference').onclick=()=>this.h.run(async()=>{this.h.closeDialog();await this.change(d=>d.deleteEntities([reference]));});$('block-replace-reference').onclick=()=>this.h.run(async()=>{const selected=this.selected;if(!selected)throw new Error('Select a replacement definition in the palette first.');let name=selected.meta.name;this.h.closeDialog();await this.change(d=>{if(selected.library!=='drawing'){const map=d.importLibrary(selected.drawing.exportLibrary([name]),{conflict:'rename'});name=map[name];}d.editInsert(reference,{name});});});}
  form.onsubmit=e=>{e.preventDefault();this.h.run(async()=>{
   if(this.doc?.id!==id)throw new Error('The active drawing changed.');const values={position:['x','y','z'].map(n=>numeric(form,n)),scale:['sx','sy','sz'].map(n=>numeric(form,n)),rotation:numeric(form,'rotation'),rows:numeric(form,'rows'),columns:numeric(form,'columns'),rowSpacing:numeric(form,'rowSpacing'),columnSpacing:numeric(form,'columnSpacing'),layer:text(form,'layer'),attributes:Object.fromEntries(m.attributes.map((a,i)=>[a.tag,text(form,'attribute'+i)])),space:reference?existing.space:this.doc.activeSpace};
   const options={screen:checked(form,'screen'),rotate:checked(form,'rotateScreen'),scale:checked(form,'scaleScreen'),repeat:checked(form,'repeat'),snap:reference?0:numeric(form,'snap'),objectSnap:checked(form,'objectSnap'),conflict:text(form,'conflict')||'keep'};
   // Validate before closing a form or importing any definition.
   const validation=entry.drawing.previewDocument(m.name,values);if(!validation.entities.length)throw new Error('Cannot insert an empty reference.');
   if(reference){this.h.closeDialog();await this.change(d=>d.editInsert(reference,values));return;}
   this.h.closeDialog();if(options.screen){await this.startPlacement(entry,values,options);}else await this.commitInsert(entry,values,options);
  });};
 }
 async referenceDialog(){await this.ensureDrawing(false);const id=[...this.selection][0];if(!id){this.referencesDialog();return;}const r=this.drawing?.entityMap.get(id);if(r?.type==='INSERT'){await this.insertDialog(id);return;}this.h.toast('Select a block INSERT to edit its properties. Create block accepts other selected source entities.');}
 async commitInsert(entry,values,options){let inserted,name=entry.meta.name;await this.change(d=>{if(entry.library!=='drawing'){const map=d.importLibrary(entry.drawing.exportLibrary([name]),{conflict:options.conflict||'rename'});name=map[name]||name;}inserted=d.insert(name,values);});this.shelf.remember(entry.library,entry.meta.name);this.selection=new Set([inserted]);this.lastInsert={name,values:structuredClone(values)};this.render();this.h.toast('Inserted '+name+' · '+values.rows+' × '+values.columns+' placements.');return name;}
 async startPlacement(entry,values,options){await this.cancel();const id=this.doc.id,serial=++this.placementSerial;this.h.setTool('select');await this.h.quiet();const preview=entry.drawing.previewDocument(entry.meta.name,{...values,position:[0,0,0],rotation:values.rotation,space:'model'});const model=await this.placementImporter.parse(encode(preview.write()),this.font,{name:'Block insertion preview',document:true,maxEntities:65534});if(this.doc?.id!==id||serial!==this.placementSerial)return;
  const committed=this.engine.annotationPages.reduce((n,p)=>n+p.count,0);if(model.count+committed>=65535)throw new Error('On-screen block preview exceeds the 65,534-entity overlay reservation. Numeric insertion remains available.');
  const packed=placementPreview(model,{idBase:this.engine.model.count+committed,layer:this.engine.annotationLayer});await this.engine.setPreview(packed);
  const center=this.engine.worldAt(this.engine.cssWidth/2,this.engine.cssHeight/2);this.placement={entry,values:structuredClone(values),options,docId:id,stage:'position',position:center,deltaAngle:0,factor:1,referenceLength:Math.max(1e-9,50/this.engine.camera.zoom),busy:false};this.pointMode=true;this.h.canvas.dataset.blockPlacement='true';this.movePreview();this.renderPlacementHint();this.h.canvas.focus();
 }
 point(e){const r=this.h.canvas.getBoundingClientRect();return this.engine.worldAt(e.clientX-r.left,e.clientY-r.top);}
 pointerMove(e){const p=this.placement;if(!p||p.busy||p.resolving||this.doc?.id!==p.docId)return false;const point=this.point(e),snap=p.options.snap||0;if(p.stage==='position'){p.position=snap>0?point.map(x=>Math.round(x/snap)*snap):point;p.lastPointer=[e.clientX,e.clientY];p.snapLabel=null;if(p.options.objectSnap&&!p.snapBusy&&performance.now()-(p.lastSnapAt||0)>100){p.lastSnapAt=performance.now();p.snapBusy=true;const box=this.h.canvas.getBoundingClientRect(),xy=[e.clientX,e.clientY];this.engine.snap(xy[0]-box.left,xy[1]-box.top).then(result=>{if(result&&this.placement===p&&p.stage==='position'&&!p.busy&&!p.resolving&&p.lastPointer?.every((v,i)=>Math.abs(v-xy[i])<2)){p.position=result.point;p.snapLabel=result.kind;this.movePreview();this.renderPlacementHint();}}).catch(error=>{p.options.objectSnap=false;this.h.toast('Object snap disabled: '+error.message);}).finally(()=>p.snapBusy=false);}}else if(p.stage==='rotation'){let angle=Math.atan2(point[1]-p.position[1],point[0]-p.position[0])*180/Math.PI;if(e.shiftKey)angle=Math.round(angle/15)*15;p.deltaAngle=angle-p.values.rotation;}else {p.factor=Math.max(1e-6,Math.hypot(point[0]-p.position[0],point[1]-p.position[1])/p.referenceLength);}this.movePreview();this.renderPlacementHint();return true;}
 pointerDown(e,pan=false){if(this.pickPoint&&e.button===0&&!pan){const callback=this.pickPoint;this.pickPoint=null;callback(this.point(e));return true;}const p=this.placement;if(!p||e.button!==0||pan)return false;if(p.busy||p.resolving)return true;this.pointerMove(e);if(p.stage==='position'&&p.options.objectSnap){p.resolving=true;const box=this.h.canvas.getBoundingClientRect();this.engine.snap(e.clientX-box.left,e.clientY-box.top).then(result=>{if(this.placement!==p)return;if(result){p.position=result.point;p.snapLabel=result.kind;this.movePreview();}this.advancePlacement(p);}).catch(error=>this.h.toast(error.message)).finally(()=>p.resolving=false);return true;}return this.advancePlacement(p);}
 advancePlacement(p){if(p.stage==='position'&&p.options.rotate)p.stage='rotation';else if(p.stage!=='scale'&&p.options.scale)p.stage='scale';else {p.busy=true;const values={...p.values,position:[...p.position,p.values.position[2]],rotation:p.values.rotation+p.deltaAngle,scale:p.values.scale.map(x=>x*p.factor)},repeat=p.options.repeat;this.h.run(async()=>{const name=await this.commitInsert(p.entry,values,p.options);if(repeat&&this.doc?.id===p.docId){const d=this.drawing,entry={drawing:d,meta:d.metadata(name),library:'drawing',libraryName:'Current drawing'};await this.startPlacement(entry,{...values,position:[0,0,0]},p.options);}}).finally(()=>{if(this.placement===p)this.cancel();});}this.renderPlacementHint();return true;}
 movePreview(){const p=this.placement;if(p)this.engine.updateBlockPreview({x:p.position[0],y:p.position[1],angle:p.deltaAngle*Math.PI/180,scale:p.factor});}
 renderPlacementHint(){const p=this.placement;if(!p)return;const action=p.stage==='position'?'Pick insertion point':p.stage==='rotation'?'Pick rotation · Shift = 15°':'Pick scale · 50 screen pixels = 1×';this.h.hint(action+(p.snapLabel?' · '+p.snapLabel+' SNAP':'')+' · '+p.entry.meta.name+' · Esc cancels · '+p.position.map(x=>x.toFixed(3)).join(', ')+' · '+(p.values.rotation+p.deltaAngle).toFixed(1)+'° · '+p.factor.toFixed(3)+'×');}
 async cancel(){this.placementSerial++;this.placementImporter.cancel();const active=!!this.placement;this.placement=null;this.pickPoint=null;delete this.h.canvas.dataset.blockPlacement;if(active){await this.h.clearPreview();this.h.hint('Wheel to zoom · Shift-click source objects · B blocks · I insert');}}
 key(e){if(e.key==='Escape'&&(this.placement||this.pickPoint)){this.h.run(()=>this.cancel());e.preventDefault();return true;}if(e.key.toLowerCase()==='b'&&!e.ctrlKey&&!e.metaKey){this.h.run(()=>e.shiftKey?this.createDialog():this.open());return true;}if(e.key.toLowerCase()==='i'&&!e.ctrlKey&&!e.metaKey){this.h.run(async()=>{if(!this.opened)await this.open();if(this.selected)await this.insertDialog();});return true;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&this.opened&&this.selectionFocus){e.preventDefault();this.h.run(()=>this.history(e.shiftKey));return true;}return false;}
 async createDialog(){const d=await this.ensureDrawing(true),id=this.doc.id,selected=[...this.selection];const source=d.entities.filter(r=>r.type!=='VIEWPORT'&&recordSpace(r)===this.doc.activeSpace);this.h.dialog('Create a reusable block',`<form id="block-create-form" class="block-form"><p class="dialog-intro">Choose source objects, then define a base point. Existing nested INSERTs stay nested. Creating a block is undoable.</p><div class="block-form-grid"><label class="span-two">Block name<input name="name" value="NEW_BLOCK" maxlength="255" required></label>${units('units',d.units)}<label class="span-three">Description<input name="description" maxlength="2048"></label>${field('bx','Base X',0)}${field('by','Base Y',0)}${field('bz','Base Z',0)}</div><div class="block-choice-line">${button('block-pick-base','Pick base point in drawing')}${button('block-select-all','Select all visible-space records')}<label>Source objects<select name="mode"><option value="convert">Convert selection to INSERT</option><option value="retain">Retain original objects</option><option value="delete">Delete originals after defining</option></select></label></div><div class="block-create-selection">${source.slice(0,5000).map(r=>{const handle=String(group(r,5));return `<label class="block-check"><input type="checkbox" name="entity" value="${esc(handle)}" ${selected.includes(handle)?'checked':''}><strong>${esc(r.type+(r.type==='INSERT'?' · '+group(r,2):''))}</strong><span>#${esc(handle)} · ${esc(group(r,8,'0'))}</span></label>`;}).join('')||'<p>The active space contains no source objects.</p>'}</div>${source.length>5000?'<p>Showing 5,000 records. Use canvas selection for larger sets.</p>':''}<div class="block-form-actions"><span></span><button type="submit" class="button primary">Create definition</button></div></form>`,'BLOCK / CREATE');const form=$('block-create-form');$('block-select-all').onclick=()=>form.querySelectorAll('[name=entity]').forEach(n=>n.checked=true);$('block-pick-base').onclick=()=>{this.h.closeDialog();this.h.hint('Pick the new block base point · Esc cancels');this.pickPoint=p=>{form.elements.bx.value=p[0];form.elements.by.value=p[1];$('dialog').showModal();this.h.hint('Base point captured.');};};form.onsubmit=e=>{e.preventDefault();this.h.run(async()=>{if(this.doc?.id!==id)throw new Error('The active drawing changed.');const ids=[...form.querySelectorAll('[name=entity]:checked')].map(n=>n.value),outside=selected.filter(v=>!source.slice(0,5000).some(r=>String(group(r,5))===v));ids.push(...outside);const name=text(form,'name'),base=['bx','by','bz'].map(n=>numeric(form,n)),options={mode:text(form,'mode'),description:text(form,'description'),units:numeric(form,'units')};this.h.closeDialog();await this.change(d=>d.create(name,ids,base,options));this.activeSource='drawing';this.selected=this.entries().find(e=>e.library==='drawing'&&e.meta.name===name);this.render();});};}
 async definitionDialog(){const entry=this.selected,d=await this.ensureDrawing(false);if(!entry||entry.library!=='drawing'||!d)return;const m=d.assertEditable(entry.meta.name),block=d.definition(m.name),docId=this.doc.id;this.h.dialog('Edit definition · '+m.name,`<form id="block-definition-form" class="block-form"><p class="dialog-intro">Changes update all references, including nested uses. The record editor preserves DXF entity parameters; no image tracing or CPU tessellation is performed. Unsupported source records remain subject to renderer diagnostics.</p><div class="block-form-grid"><label class="span-two">Block name<input name="name" value="${esc(m.name)}" required></label>${units('units',m.units)}<label class="span-three">Description<input name="description" value="${esc(m.description)}"></label>${field('bx','Base X',m.base[0])}${field('by','Base Y',m.base[1])}${field('bz','Base Z',m.base[2])}</div><div class="block-placement-options">${check('explode','Allow explode',m.allowExplode)}${check('uniform','Require uniform scale',m.uniform)}</div><details class="block-form-section"><summary>DXF definition records · ${block.records.length}</summary><p>JSON source records. INSERT dependencies must already exist in the drawing. Cycles and invalid records are rejected atomically.</p><textarea name="records" class="block-code" spellcheck="false">${esc(JSON.stringify(block.records,null,2))}</textarea></details><div class="block-form-actions"><span></span><button type="submit" class="button primary">Save definition</button></div></form>`,'BLOCK / EDIT DEFINITION');const form=$('block-definition-form');form.onsubmit=e=>{e.preventDefault();this.h.run(async()=>{if(this.doc?.id!==docId)throw new Error('The active drawing changed.');const name=text(form,'name'),values={base:['bx','by','bz'].map(n=>numeric(form,n)),description:text(form,'description'),units:numeric(form,'units'),allowExplode:checked(form,'explode'),uniform:checked(form,'uniform'),records:JSON.parse(text(form,'records'))};this.h.closeDialog();await this.change(d=>{d.setDefinition(m.name,values);if(name!==m.name)d.rename(m.name,name);});this.selected=this.entries().find(e=>e.library==='drawing'&&e.meta.name===name);this.render();});};}
 async openStudio(){await this.ensureDrawing(false);const entry=this.selected;if(!entry||entry.library!=='drawing')throw new Error('Add the selected library definition to the drawing before editing it.');this.drawing.assertEditable(entry.meta.name);await this.cancel();this.studio=new BlockStudio(this,entry);await this.studio.open();}
 selectedRanges(){const model=this.engine.model;if(!model)return [];if(this.editMapModel!==model){this.editMapModel=model;this.editMap=new Map((model.editRoots||[]).map(r=>[r.handle,r]));}const ranges=[];for(const id of this.selection){const range=this.editMap.get(id)||this.primitiveSelections?.get(id);if(range)ranges.push({first:range.first,count:range.count});}return ranges;}
 commandDialog(){const commands=[['INSERT','Insert selected block','Position, scale, rotation, attributes and rectangular arrays',()=>this.insertDialog()],['BLOCK','Create from selection','Base point and convert / retain / delete originals',()=>this.createDialog()],['BEDIT','Graphical Block Studio','Draw and edit a definition without modifying its parent until Save',()=>this.openStudio()],['BPROPERTIES','Definition properties','Rename, base point, units, raw source records',()=>this.definitionDialog()],['EATTEDIT','Reference properties','Edit an existing INSERT and attribute values',()=>this.referenceDialog()],['BATTMAN','Attribute definitions','Add / edit / remove / reorder ATTDEF templates',()=>this.attributesDialog()],['BCOUNT','Count and extract','Expanded nested counts and attribute CSV',()=>this.countDialog()],['EXPLODE','Explode rendered 2D geometry','GPU affine baking; recursively removes nested references',()=>this.explodeDialog(false)],['BURST','Explode and retain attributes','GPU baking; visible attributes become ordinary text',()=>this.explodeDialog(true)],['BREPLACE','Replace selected references','Change definition while preserving placements and matching tags',()=>this.replaceDialog()],['BCOPY','Copy selected references','Keep definition sharing; apply placement offsets',()=>this.copyDialog()],['BARRAY','Polar array','Create rotated INSERT references around a chosen center',()=>this.polarDialog()],['WBLOCK','Export selected block','Dependency-complete DXF or JSON library',()=>this.exportLibrary()],['BREFS','Reference tree','Inspect root and nested INSERT identities',()=>this.referencesDialog()],['PURGE','Purge unused definitions','Dependency-aware, undoable cleanup',()=>this.purge()],['LIBRARIES','Manage local libraries','Rename or remove imported collections',()=>this.manageLibraries()]];this.h.dialog('Block commands',`<p class="dialog-intro">Static DXF block authoring and insertion commands. These operate on editable source definitions and references, independently of review annotations.</p><div class="block-command-list">${commands.map(([key,title,sub])=>`<button class="button" data-block-command="${key}"><strong>${title}</strong> <em>${key}</em><small>${sub}</small></button>`).join('')}</div>`,'BLOCKS / COMMAND CENTER');document.querySelectorAll('[data-block-command]').forEach(b=>b.onclick=()=>this.h.run(async()=>{this.h.closeDialog();const item=commands.find(x=>x[0]===b.dataset.blockCommand);await this.ensureDrawing(true);await item[3]();}));}
 countDialog(){const d=this.drawing;if(!d)return;const counts=d.countReferences(),attributes=d.attributeRows();this.h.dialog('Block counts and attribute extraction',`<p class="dialog-intro">Counts expand nested references and rectangular arrays arithmetically, without expanding GPU geometry or reading entity buffers. Attribute rows describe root INSERT records, with their row/column multiplicity.</p><div class="block-record-list">${counts.map(r=>`<div><strong>${esc(r.name)}</strong><span>${r.placements.toLocaleString()} placements</span></div>`).join('')}</div><div class="block-detail-actions">${button('block-count-csv','Export counts · CSV')}${button('block-attribute-csv','Export attributes · CSV')}${button('block-select-inserts','Select all active-space INSERTs')}</div>`,'BLOCKS / DATA EXTRACTION');const csv=rows=>{if(!rows.length)return '';const keys=Object.keys(rows[0]),cell=v=>'"'+String(v??'').replaceAll('"','""')+'"';return [keys,...rows.map(r=>keys.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');};$('block-count-csv').onclick=()=>this.h.download(csv(counts),'block-counts.csv','text/csv');$('block-attribute-csv').onclick=()=>this.h.download(csv(attributes),'block-attributes.csv','text/csv');$('block-select-inserts').onclick=()=>{const roots=d.entities.filter(r=>r.type==='INSERT'&&recordSpace(r)===this.doc.activeSpace);if(roots.length>4096)throw new Error('Refine the selection to at most 4,096 references.');this.selection=new Set(roots.map(r=>String(group(r,5))));this.h.closeDialog();this.renderSelection();};}
 async explodeDialog(keepAttributes){const d=await this.ensureDrawing(false),ids=[...this.selection];if(!d||!ids.length)throw new Error('Select one or more root INSERT references first.');const roots=validateExplodable(d,ids);if(roots.some(r=>recordSpace(r)!==this.doc.activeSpace))throw new Error('Open the source Model or paper tab before exploding its references.');const ranges=this.selectedRanges(),count=ranges.reduce((n,r)=>n+r.count,0);if(!count)throw new Error('The selection has no supported resident geometry.');const revision=d.revision,id=this.doc.id;this.h.dialog(keepAttributes?'GPU BURST':'GPU recursive explode',`<p class="dialog-intro">Convert ${ids.length} INSERT records (${count.toLocaleString()} rendered primitives) into independent planar DXF entities. Nested references are recursively flattened. ${keepAttributes?'Visible attribute values become ordinary text.':'Attached attribute values are omitted.'} This is an explicit geometry readback, not a per-frame operation. Unsupported, nonplanar and nonrepresentable primitives reject the command without changing the drawing.</p><p>This operation is undoable. It does not implement AutoCAD’s one-level EXPLODE behavior or dynamic-block actions.</p>${button('block-explode-confirm','Bake on GPU and replace references','primary')}`,'BLOCK / GPU AFFINE BAKE');$('block-explode-confirm').onclick=()=>this.h.run(async()=>{this.h.closeDialog();await this.cancel();const result=await this.engine.explode(ranges),records=explodedRecords(result,{drawing:d,layers:this.engine.layers,space:this.doc.activeSpace,keepAttributes});await this.change(current=>{if(current!==d||current.revision!==revision||this.doc.id!==id)throw new Error('The drawing changed during explode. Nothing was replaced.');current.replaceEntities(ids,records,{label:keepAttributes?'GPU BURST':'GPU recursive explode'});});this.h.toast('GPU bake committed: '+records.length+' independent DXF entities.');});}
 async replaceDialog(){const d=await this.ensureDrawing(false),ids=[...this.selection];if(!ids.length||ids.some(id=>d?.entityMap.get(id)?.type!=='INSERT'))throw new Error('Select INSERT references to replace.');this.h.dialog('Replace '+ids.length+' references',`<form id="block-replace-form" class="block-form"><p>Preserves position, XYZ scale, rotation, arrays, layers and matching attribute tag values. The replacement is one undoable command.</p><label>New definition<select name="definition">${d.list().filter(b=>!b.external&&!b.dynamic).map(b=>`<option value="${esc(b.name)}">${esc(b.name)}</option>`).join('')}</select></label><button type="submit" class="button primary">Replace references</button></form>`,'BLOCK / REPLACE');const form=$('block-replace-form');form.onsubmit=e=>{e.preventDefault();const name=text(form,'definition');this.h.run(async()=>{this.h.closeDialog();await this.change(current=>{for(const id of ids)current.editInsert(id,{name});});});};}
 async copyDialog(){const d=await this.ensureDrawing(false),ids=[...this.selection];if(!ids.length||ids.some(id=>d?.entityMap.get(id)?.type!=='INSERT'))throw new Error('Select INSERT references to copy.');this.h.dialog('Copy '+ids.length+' references',`<form id="block-copy-form" class="block-form"><div class="block-form-grid">${field('dx','Offset X',20)}${field('dy','Offset Y',0)}${field('copies','Copies',1,'min="1" max="10000"')}</div><button type="submit" class="button primary">Create linked-definition copies</button></form>`,'BLOCK / COPY');const form=$('block-copy-form');form.onsubmit=e=>{e.preventDefault();const dx=numeric(form,'dx'),dy=numeric(form,'dy'),copies=numeric(form,'copies');this.h.run(async()=>{if(!Number.isInteger(copies)||copies<1||copies*ids.length>10000)throw new Error('Copy is limited to 10,000 INSERT records per command.');this.h.closeDialog();await this.change(current=>{for(let i=1;i<=copies;i++)for(const id of ids){const r=current.entityMap.get(id),o=readInsert(r);current.insert(String(group(r,2)),{...o,position:[o.position[0]+i*dx,o.position[1]+i*dy,o.position[2]]});}});});};}
 async polarDialog(){const d=await this.ensureDrawing(false),ids=[...this.selection];if(!ids.length||ids.some(id=>d?.entityMap.get(id)?.type!=='INSERT'))throw new Error('Select INSERT references for a polar array.');this.h.dialog('Polar INSERT array',`<form id="block-polar-form" class="block-form"><p>Creates independent INSERT records sharing the same definitions. The existing references are the first array items.</p><div class="block-form-grid">${field('x','Center X',0)}${field('y','Center Y',0)}${field('count','Total items',6,'min="2" max="10000"')}${field('angle','Step angle °',60)}</div>${check('rotate','Rotate each placement',true)}<button type="submit" class="button primary">Create polar array</button></form>`,'BLOCK / POLAR ARRAY');const form=$('block-polar-form');form.onsubmit=e=>{e.preventDefault();const x=numeric(form,'x'),y=numeric(form,'y'),count=numeric(form,'count'),step=numeric(form,'angle'),rotate=checked(form,'rotate');this.h.run(async()=>{if(!Number.isInteger(count)||count<2||count*ids.length>10000)throw new Error('Polar arrays are limited to 10,000 INSERT records.');this.h.closeDialog();await this.change(current=>{for(let i=1;i<count;i++){const angle=i*step*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle);for(const id of ids){const r=current.entityMap.get(id),o=readInsert(r),dx=o.position[0]-x,dy=o.position[1]-y;current.insert(String(group(r,2)),{...o,position:[x+c*dx-s*dy,y+s*dx+c*dy,o.position[2]],rotation:o.rotation+(rotate?i*step:0)});}}});});};}
 manageLibraries(){this.h.dialog('Manage block libraries',`<p class="dialog-intro">Library changes affect this browser’s shelf only. Existing definitions already imported into drawings are not removed. Save libraries locally to persist changes.</p><div class="block-record-list">${this.shelf.libraries.map(l=>`<div><label>Library name<input data-library-name="${esc(l.id)}" value="${esc(l.name)}"></label><button class="button small" data-library-remove="${esc(l.id)}">Remove collection</button></div>`).join('')}</div>`,'BLOCKS / LOCAL LIBRARIES');document.querySelectorAll('[data-library-name]').forEach(input=>input.onchange=()=>{const l=this.shelf.libraries.find(l=>l.id===input.dataset.libraryName);if(l)l.name=input.value.slice(0,255)||'Library';this.render();});document.querySelectorAll('[data-library-remove]').forEach(b=>b.onclick=()=>{this.shelf.remove(b.dataset.libraryRemove);this.selected=null;this.render();this.manageLibraries();});}
 async attributesDialog(){
  const d=await this.ensureDrawing(false),name=this.selected?.meta.name;if(!d||!name)return;
  const meta=d.assertEditable(name),definitions=d.definition(name).records.filter(r=>r.type==='ATTDEF');
  this.h.dialog(name+' / attribute definitions',`<p class="dialog-intro">Edit, remove, and reorder ATTDEF templates. New references use the current templates. Synchronize updates existing root and nested references while preserving matching tag values; renamed or deleted tags do not keep their old values.</p><div class="block-record-list">${meta.attributes.map((a,i)=>`<div><strong>${esc(a.tag)}</strong><span>${esc(a.prompt)} · ${esc(a.value)}${a.constant?' · constant':''}${a.invisible?' · invisible':''}</span><div class="block-attribute-actions"><button class="button small" data-attribute-edit="${i}">Edit</button><button class="button small" data-attribute-up="${i}" ${i===0?'disabled':''} aria-label="Move ${esc(a.tag)} up">↑</button><button class="button small" data-attribute-down="${i}" ${i===meta.attributes.length-1?'disabled':''} aria-label="Move ${esc(a.tag)} down">↓</button><button class="button small" data-attribute-remove="${i}">Remove</button></div></div>`).join('')||'<p>No attribute templates.</p>'}</div><form class="block-form" id="block-attdef-form"><input type="hidden" name="originalTag"><div class="block-form-grid"><label>Tag<input name="tag" required pattern="[^\\s]+" maxlength="255"></label><label>Prompt<input name="prompt"></label><label>Default value<input name="value"></label>${field('x','Local X',0)}${field('y','Local Y',0)}${field('height','Text height',2.5,'min="0.000001"')}${field('angle','Rotation',0)}</div><div class="block-placement-options">${check('invisible','Invisible')}${check('constant','Constant')}${check('verify','Verify')}${check('preset','Preset')}</div><div class="block-form-actions">${button('block-sync-attributes','Synchronize existing references')}${button('block-new-attribute','New template')}<span></span><button class="button primary" type="submit">Add attribute template</button></div></form>`,'BLOCK / ATTRIBUTES');
  const form=$('block-attdef-form');form.onsubmit=e=>{e.preventDefault();this.h.run(async()=>{const tag=text(form,'tag').toUpperCase(),old=text(form,'originalTag'),flags=Number(checked(form,'invisible'))+2*Number(checked(form,'constant'))+4*Number(checked(form,'verify'))+8*Number(checked(form,'preset')),values={tag,prompt:text(form,'prompt')||tag,value:text(form,'value'),x:numeric(form,'x'),y:numeric(form,'y'),height:numeric(form,'height'),rotation:numeric(form,'angle'),flags};this.h.closeDialog();await this.change(current=>old?current.setAttribute(name,old,values):current.addAttribute(name,values));});};
  $('block-sync-attributes').onclick=()=>this.h.run(async()=>{this.h.closeDialog();await this.change(current=>current.syncAttributes(name));});
  $('block-new-attribute').onclick=()=>{form.reset();form.querySelector('[type=submit]').textContent='Add attribute template';form.elements.tag.focus();};
  document.querySelectorAll('[data-attribute-edit]').forEach(button=>button.onclick=()=>{const r=definitions[Number(button.dataset.attributeEdit)];for(const [key,code] of [['tag',2],['originalTag',2],['prompt',3],['value',1],['x',10],['y',20],['height',40],['angle',50]])form.elements.namedItem(key).value=String(group(r,code,code<10?'':0));for(const [key,bit] of [['invisible',1],['constant',2],['verify',4],['preset',8]])form.elements.namedItem(key).checked=!!(group(r,70)&bit);form.querySelector('[type=submit]').textContent='Save attribute template';form.elements.tag.focus();});
  for(const [kind,delta] of [['up',-1],['down',1],['remove',0]])document.querySelectorAll('[data-attribute-'+kind+']').forEach(button=>button.onclick=()=>this.h.run(async()=>{const tag=meta.attributes[Number(button.dataset['attribute'+kind[0].toUpperCase()+kind.slice(1)])].tag;this.h.closeDialog();await this.change(current=>delta?current.moveAttribute(name,tag,delta):current.removeAttribute(name,tag));await this.attributesDialog();}));
 }
}
