/** Isolated graphical definition editing. The main drawing changes only on Save.
 * CPU code edits DXF parameter records; the production compute engine evaluates
 * all geometry, nested transforms, text and preview rendering. */
import { BlockDrawing,group,setGroup,record,canonical,validateRecords,readInsert } from '../blocks/document.js';
import { ownerOf } from '../blocks/preview.js';
import { DxfWorkerClient } from '../dxf/client.js';
import { ComputeCad } from '../gpu/index.js';
import { ModelBuilder,TYPE } from '../model/index.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const TYPES={LINE:[[10,'Start X'],[20,'Start Y'],[11,'End X'],[21,'End Y']],CIRCLE:[[10,'Center X'],[20,'Center Y'],[40,'Radius']],ARC:[[10,'Center X'],[20,'Center Y'],[40,'Radius'],[50,'Start angle °'],[51,'End angle °']],ELLIPSE:[[10,'Center X'],[20,'Center Y'],[11,'Major X'],[21,'Major Y'],[40,'Axis ratio'],[41,'Start parameter'],[42,'End parameter']],TEXT:[[10,'X'],[20,'Y'],[40,'Height'],[41,'Width factor'],[50,'Angle °'],[1,'Text']],ATTDEF:[[10,'X'],[20,'Y'],[40,'Height'],[50,'Angle °'],[2,'Tag'],[3,'Prompt'],[1,'Default'],[70,'Flags']],INSERT:[[10,'X'],[20,'Y'],[41,'Scale X'],[42,'Scale Y'],[43,'Scale Z'],[50,'Angle °'],[70,'Columns'],[71,'Rows'],[44,'Column spacing'],[45,'Row spacing']],POINT:[[10,'X'],[20,'Y']]};
export class BlockStudio {
 constructor(workbench,entry){this.w=workbench;this.entry=entry;this.parent=workbench.drawing;this.docId=workbench.doc.id;this.name=entry.meta.name;this.revision=this.parent.revision;this.work=this.parent.definitionDrawing(this.name);this.importer=new DxfWorkerClient();this.queue=Promise.resolve();this.dead=false;this.busy=false;this.tool='select';this.first=null;this.selected=null;this.ready=false;this.previewPending=null;this.previewBusy=false;}
 async open(){const h=this.w.h;this.w.previewSerial++;this.w.previewDevice?.dispose();this.w.previewDevice=null;
 h.dialog('Block Studio · '+this.name,`<div class="block-studio"><p class="dialog-intro">Definition coordinates · base ${this.entry.meta.base.map(v=>Number(v).toFixed(3)).join(', ')}. Click to construct geometry, select objects to edit parameters, or insert a nested definition. Attribute templates display as &lt;TAG&gt;. Save updates every reference; closing discards these isolated edits.</p><div class="studio-toolbar">${[['select','Select'],['line','Line'],['rectangle','Rectangle'],['circle','Circle'],['point','Point'],['text','Text'],['attribute','Attribute']].map(([id,text])=>`<button class="button small" data-studio-tool="${id}" aria-pressed="${id==='select'}">${text}</button>`).join('')}<button id="studio-nested" class="button small">Nested INSERT</button><button id="studio-fit" class="button small">Fit</button><button id="studio-undo" class="button small">Undo</button><button id="studio-redo" class="button small">Redo</button></div><div class="studio-body"><div class="studio-stage"><canvas id="studio-canvas" tabindex="0" aria-label="GPU compute block definition editor"></canvas><div id="studio-status" role="status">Initializing compute editor…</div><div class="studio-inputs"><label>Layer<select id="studio-layer">${this.work.layers.map(l=>`<option value="${esc(l.name)}">${esc(l.name)}</option>`).join('')}</select></label><label>Grid<input id="studio-grid" type="number" min="0" step="any" value="0"></label><label>Text / tag<input id="studio-text" value="LABEL" maxlength="1024"></label><label>Height<input id="studio-height" type="number" min="0.000001" step="any" value="2.5"></label></div></div><aside class="studio-properties"><div id="studio-records" class="studio-records" aria-label="Definition members"></div><div id="studio-property-form"></div></aside></div><div class="block-form-actions"><button id="studio-discard" class="button">Discard</button><span id="studio-summary"></span><button id="studio-save" class="button primary">Save definition</button></div></div>`,'BLOCK / GRAPHICAL DEFINITION EDITOR');
 const dialog=$('dialog');dialog.classList.add('studio-dialog');this.closeListener=()=>this.dispose();dialog.addEventListener('close',this.closeListener,{once:true});this.canvas=$('studio-canvas');this.engine=new ComputeCad(this.canvas,{memoryBudget:192*1024*1024,maxPixels:1800000,pixelRatio:Math.min(devicePixelRatio||1,2),paperCacheBudget:0});this.engine.addEventListener('error',e=>this.status(e.detail.message));
 dialog.querySelectorAll('[data-studio-tool]').forEach(b=>b.onclick=()=>{this.tool=b.dataset.studioTool;this.first=null;dialog.querySelectorAll('[data-studio-tool]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));this.status(this.tool==='select'?'Click an object to edit its DXF parameters.':'Click '+(this.tool==='line'||this.tool==='rectangle'?'first point':this.tool==='circle'?'center':'placement point'));this.canvas.focus();});
 $('studio-discard').onclick=()=>h.closeDialog();$('studio-save').onclick=()=>h.run(()=>this.save());$('studio-fit').onclick=()=>{if(this.ready){this.engine.fit();this.engine.requestFrame();}};$('studio-undo').onclick=()=>this.run(async()=>{if(this.work.undo())await this.refresh();});$('studio-redo').onclick=()=>this.run(async()=>{if(this.work.redo())await this.refresh();});$('studio-nested').onclick=()=>this.nestedForm();
 this.canvas.addEventListener('wheel',e=>{e.preventDefault();if(this.ready){const r=this.canvas.getBoundingClientRect();this.engine.zoomAt(e.clientX-r.left,e.clientY-r.top,Math.exp(-Math.max(-200,Math.min(200,e.deltaY))*.005));}},{passive:false});this.canvas.addEventListener('contextmenu',e=>e.preventDefault());
 this.canvas.addEventListener('pointerdown',e=>{if(!this.ready||this.busy)return;if(e.button===1||e.button===2||e.altKey){this.pan={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId);return;}if(e.button===0)this.run(()=>this.click(e));});
 this.canvas.addEventListener('pointerup',()=>this.pan=null);this.canvas.addEventListener('pointercancel',()=>this.pan=null);this.canvas.addEventListener('pointermove',e=>{if(this.pan){this.engine.pan(e.clientX-this.pan.x,e.clientY-this.pan.y);this.pan={x:e.clientX,y:e.clientY};return;}if(this.first&&this.ready){this.previewPending=this.point(e);this.updatePreview();}});
 this.canvas.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();this.first=null;this.clearPreview();this.status('Construction canceled.');}if(e.key==='Delete'&&this.selected){e.preventDefault();this.run(()=>this.remove());}});
 this.renderRecords();try{await this.engine.initialize(this.w.font);if(this.dead)return;this.ready=true;this.resize=new ResizeObserver(()=>{if(!this.dead){const r=this.canvas.getBoundingClientRect();this.engine.setSize(Math.max(1,r.width),Math.max(1,r.height));}});this.resize.observe(this.canvas);await this.refresh(true);}catch(error){this.status(error.message+' · Record editing remains available; no alternate renderer is used.');}
 }
 run(fn){const next=this.queue.catch(()=>{}).then(async()=>{if(this.dead)return;this.busy=true;try{return await fn();}finally{this.busy=false;}});this.queue=next;this.w.h.run(()=>next);return next;}
 status(message){if(!this.dead&&$('studio-status'))$('studio-status').textContent=message;}
 point(e){const r=this.canvas.getBoundingClientRect(),p=this.engine.worldAt(e.clientX-r.left,e.clientY-r.top),grid=Number($('studio-grid').value);return grid>0?p.map(v=>Math.round(v/grid)*grid):p;}
 viewDrawing(){const out=BlockDrawing.fromState(this.work.toState());out.entities=out.entities.map(r=>{if(r.type!=='ATTDEF')return r;let next={...r,type:'TEXT',groups:r.groups.filter(g=>g.code!==100&&![2,3,70,74,280].includes(g.code))};next=setGroup(next,1,'<'+group(r,2,'TAG')+'>');next=setGroup(next,73,group(r,74,0));return next;});out.refresh();return out;}
 async refresh(fit=false){this.renderRecords();if(!this.ready||this.dead)return;await this.clearPreview();const view=this.viewDrawing(),model=await this.importer.parse(new TextEncoder().encode(view.write()).buffer,this.w.font,{document:true,editMap:true,name:this.name});if(this.dead)return;const camera={...this.engine.camera};if(this.engine.model)await this.engine.reconcileModel(model);else await this.engine.setModel(model);if(fit)this.engine.fit();else this.engine.camera=camera;this.engine.requestFrame();this.status(model.count+' GPU primitives · middle/right drag to pan · wheel zoom · Escape cancels construction');}
 renderRecords(){if(this.dead)return;const root=$('studio-records');root.innerHTML=this.work.entities.slice(0,5000).map(r=>{const id=String(group(r,5));return `<button class="studio-record ${id===this.selected?'selected':''}" data-studio-record="${esc(id)}"><strong>${esc(r.type)}</strong><span>${esc(r.type==='INSERT'?group(r,2):r.type==='ATTDEF'?group(r,2):'#'+id)}</span><small>${esc(group(r,8,'0'))}</small></button>`;}).join('')||'<p class="empty">Empty definition. Draw your first object.</p>';root.querySelectorAll('[data-studio-record]').forEach(b=>b.onclick=()=>this.select(b.dataset.studioRecord));$('studio-summary').textContent=this.work.entities.length+' direct members · '+this.work.undoStack.length+' isolated edits';$('studio-undo').disabled=!this.work.undoStack.length;$('studio-redo').disabled=!this.work.redoStack.length;if(this.selected&&!this.work.entityMap.has(this.selected))this.selected=null;this.properties();}
 select(id){this.selected=id;this.tool='select';this.first=null;this.renderRecords();if(this.ready){const entry=this.engine.model.editRoots?.find(r=>r.handle===id);this.engine.selectEntities(entry?[entry]:[]);}}
 properties(){const host=$('studio-property-form'),r=this.work.entityMap.get(this.selected);if(!r){host.innerHTML='<p>Select a member to edit. Source records not supported by a property form remain available through the DXF record editor.</p>';return;}const fields=TYPES[r.type]||[];host.innerHTML=`<form id="studio-object-form" class="block-form"><h3>${esc(r.type)} · #${esc(this.selected)}</h3><label>Layer<input name="layer" value="${esc(group(r,8,'0'))}" required></label><div class="studio-numeric">${fields.map(([code,label])=>`<label>${label}<input name="g${code}" ${typeof group(r,code,'')==='number'||code>=10?'type="number" step="any"':''} value="${esc(group(r,code,code===41||code===42||code===43?1:code===1||code===2||code===3?'':0))}"></label>`).join('')}</div><details><summary>DXF record · advanced</summary><textarea name="raw" class="block-code" spellcheck="false">${esc(JSON.stringify(r,null,2))}</textarea><label class="block-check"><input type="checkbox" name="rawMode"> Apply raw JSON instead</label></details><div class="block-detail-actions"><button type="submit" class="button primary small">Apply member</button><button type="button" id="studio-delete" class="button small">Delete</button></div></form>`;
 const form=$('studio-object-form');form.onsubmit=e=>{e.preventDefault();this.run(async()=>{let next;if(form.elements.rawMode.checked)next=JSON.parse(form.elements.raw.value);else{next=setGroup(r,8,form.elements.layer.value);for(const [code] of fields){const value=form.elements.namedItem('g'+code).value;next=setGroup(next,code,code===1||code===2||code===3?value:Number(value));}}next=setGroup(next,5,this.selected);validateRecords([next]);if(!form.elements.rawMode.checked&&r.type==='INSERT')this.work.editInsert(this.selected,readInsert(next));else{if(['CIRCLE','ARC','ELLIPSE','TEXT','ATTDEF'].includes(next.type)&&Number(group(next,40,0))<=0)throw new Error('Radius, axis ratio, or text height must be positive.');const data=this.work.entities.map(x=>x===r?next:x);this.work.transaction('Edit member',()=>{this.work.entities=data;this.work.ensureLayer(group(next,8,'0'));});}await this.refresh();});};$('studio-delete').onclick=()=>this.run(()=>this.remove());}
 async remove(){if(!this.selected)return;this.work.deleteEntities([this.selected]);this.selected=null;await this.refresh();}
 async click(event){const p=this.point(event);if(this.tool==='select'){const box=this.canvas.getBoundingClientRect(),id=await this.engine.pick(event.clientX-box.left,event.clientY-box.top);const owner=ownerOf(this.engine.model,id);if(owner)this.select(owner.handle);return;}
 const layer=$('studio-layer').value,height=Number($('studio-height').value),value=$('studio-text').value||'LABEL',common=[[8,layer],[62,0]];let r;
 if(['line','rectangle','circle'].includes(this.tool)&&!this.first){this.first=p;this.status('Click '+(this.tool==='circle'?'radius point':'second point')+' · Esc cancels');return;}
 if(this.tool==='line')r=record('LINE',[...common,[10,this.first[0]],[20,this.first[1]],[11,p[0]],[21,p[1]]]);
 else if(this.tool==='rectangle'){const a=this.first;r=record('LWPOLYLINE',[...common,[90,4],[70,1],[10,a[0]],[20,a[1]],[10,p[0]],[20,a[1]],[10,p[0]],[20,p[1]],[10,a[0]],[20,p[1]]]);}
 else if(this.tool==='circle'){const radius=Math.hypot(p[0]-this.first[0],p[1]-this.first[1]);if(radius<1e-9)throw new Error('Choose a nonzero circle radius.');r=record('CIRCLE',[...common,[10,this.first[0]],[20,this.first[1]],[40,radius]]);}
 else if(this.tool==='point')r=record('POINT',[...common,[10,p[0]],[20,p[1]]]);
 else if(this.tool==='text'||this.tool==='attribute'){if(!Number.isFinite(height)||height<=0)throw new Error('Text height must be positive.');const attr=this.tool==='attribute';r=record(attr?'ATTDEF':'TEXT',[...common,[10,p[0]],[20,p[1]],[40,height],[1,attr?'':value],...(attr?[[2,value.toUpperCase().replace(/\s/g,'_')],[3,value],[70,0]]:[])]);}
 if(r){this.work.replaceEntities([],[r],{label:'Draw '+r.type});this.first=null;await this.refresh();}
 }
 async updatePreview(){if(this.previewBusy||this.busy||!this.ready||!this.first||!this.previewPending||this.dead)return;this.previewBusy=true;const p=this.previewPending;this.previewPending=null;try{const builder=new ModelBuilder(this.w.font,{origin:this.engine.model.origin}),a=this.first,layer=this.engine.annotationLayer,color=0xff65cbff;if(this.tool==='circle'){builder.add({type:TYPE.ELLIPSE,anchor:a,p:[Math.hypot(p[0]-a[0],p[1]-a[1]),0,1,0],q:[0,Math.PI*2,0,0],layer,color});}else if(this.tool==='rectangle'){builder.add({type:TYPE.POLYLINE,anchor:a,points:[a,[p[0],a[1]],p,[a[0],p[1]]],flags:1,layer,color});}else builder.add({type:TYPE.LINE,anchor:a,p:[p[0]-a[0],p[1]-a[1],0,0],layer,color});const model=builder.finish(),idBase=this.engine.model.count;for(const page of model.pages){const u=new Uint32Array(page.entities);for(let i=0;i<page.count;i++)u[i*32+19]+=idBase;page.idBase+=idBase;}await this.engine.setPreview(model);}catch(error){this.status(error.message);}finally{this.previewBusy=false;if(this.previewPending&&!this.busy)this.updatePreview();}}
 async clearPreview(){this.first=null;this.previewPending=null;if(this.ready&&!this.dead){while(this.previewBusy)await new Promise(resolve=>setTimeout(resolve,0));await this.engine.setPreview({pages:[],count:0,origin:this.engine.model?.origin||[0,0]});}}
 nestedForm(){const names=this.work.list().filter(b=>canonical(b.name)!==canonical(this.name)&&!b.external&&!b.dynamic).map(b=>b.name),host=$('studio-property-form');host.innerHTML=`<form id="studio-nest-form" class="block-form"><h3>Nested INSERT</h3><label>Definition<select name="definition">${names.map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('')}</select></label>${[['x','X',0],['y','Y',0],['scale','Uniform scale',1],['angle','Angle °',0]].map(([n,l,v])=>`<label>${l}<input type="number" name="${n}" step="any" value="${v}" required></label>`).join('')}<button class="button primary" type="submit">Insert member</button></form>`;const form=$('studio-nest-form');form.onsubmit=e=>{e.preventDefault();this.run(async()=>{this.work.insert(form.elements.definition.value,{position:[Number(form.elements.x.value),Number(form.elements.y.value),0],scale:Array(3).fill(Number(form.elements.scale.value)),rotation:Number(form.elements.angle.value),layer:$('studio-layer').value});await this.refresh();});};}
 async save(){await this.queue.catch(()=>{});if(this.dead)return;if(this.w.doc?.id!==this.docId||this.parent.revision!==this.revision)throw new Error('The parent drawing changed while this definition was open. Reopen the editor to avoid overwriting newer edits.');const records=structuredClone(this.work.entities);await this.w.change(d=>d.setDefinition(this.name,{records}));this.w.h.closeDialog();this.w.h.toast('Saved '+this.name+'; all references updated.');}
 dispose(){if(this.dead)return;this.dead=true;this.importer.cancel();this.resize?.disconnect();this.engine?.dispose();$('dialog')?.classList.remove('studio-dialog');this.w.studio=null;if(this.w.opened&&this.w.selected)this.w.queueThumbnail(this.w.selected);}
}
